### ISSUE TITLE
[Feature]: Installation Instructions for Build Dependencies in README.md

### ISSUE THREAD

**Issue by AshtonStephens** [stacks-network/sbtc#100]
# Feature - Installation Instructions for Build Dependencies in README.md

## 1. Description

Some of the project artifacts require specific build dependencies:
- Java 21
- Smithy
- npm
- cdk

We should have a Getting Started section in the README to clarify how to install these tools for some key operating systems and architectures.
- Arch Linux x86
- Debian x86
- MacOS Arm64

### 1.1 Context & Purpose

We want collaborating on this project to be easy, but dependency installation can be annoying. This ticket is to make onboarding easier.

## 2. Technical Details:

We'll add some installation instructions in the root readme for the tools. We won't provide any scripts.

### 2.1 Acceptance Criteria:
We have working and verified installation procedure for the following systems and architectures.
- [x] Arch Linux x86
- [ ] Debian x86
- [x] MacOS Arm64

## 3. Related Issues and Pull Requests (optional):

- #99 
- #70

**Comment by djordon** [comment]
Do you happen to know the minimum versions of `npm` and `smithy` that are necessary? For `npm` I installed the latest LTS version, 22.0.0, which was released very recently. I'm sure an earlier version is fine, maybe we just recommend the LTS version before this? I can check to see if that works fine tomorrow.

**Comment by AshtonStephens** [comment]
@djordon @xoloki do we want an installation script or installation instructions or both?

**Comment by djordon** [comment]
Oof, well I'd go with just installation instructions but I don't have a strong preference. Although I like the idea of an install script, they tend to become under-maintained. Ours might be difficult to get right for all of our supported operating systems and CPU architectures, so it might not be worth the effort right now. Perhaps when things settle down and become more stable we can revisit and add one?

**Comment by AshtonStephens** [comment]
I was thinking the same, I dislike that installation scripts must either prescribe an installation location or be overly configurable to the point they're confusing.

I'll make instructions for a debian system because I can test that in a docker container and leave it to the reader to determine how to match that to their OS.

**Comment by AshtonStephens** [comment]
I'm trying to get a script working on a new machine just to verify that I have all the installation steps accounted for, but I keep running into issues because the easiest way to run these is on MacOS, but I'm testing this on an `Amazon Linux 2023` machine, which is not meaningfully different from Fedora Linux in this context.

```bash
# Debugging and script helpers.
sudo dnf install -y git ncat curl jq sed

# Build requirements.
sudo dnf install -y build-essential clang llvm  openssl openssl-devel pkg-config java-21-amazon-corretto

# Export the OPENSSL include directory so it can be utilized by the `cargo` openssl package.
OPENSSL_INCLUDE_DIR=/usr/include/openssl/
export OPENSSL_INCLUDE_DIR

# Install rustup.
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

# shellcheck source=/dev/null
source "$HOME/.bashrc"

# Install cargo lambda build depencency.
(
    # Install faster cargo installer that uses compiled binary
    # GitHub https://github.com/cargo-bins/cargo-binstall
    curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
    cargo binstall cargo-binstall # Make sure we've got the best one.
    cargo binstall cargo-lambda
) &

# Install pnpm.
(
    wget -qO- https://get.pnpm.io/install.sh | sh -
    pnpm env use --global 20 # Set node version to 20
) &

# Clone the sBTC repository.
( git clone https://github.com/stacks-network/sbtc.git ) &

# Wait for the async processes to finish.
wait

# Pickup the environment changes from the pnpm installation.
# shellcheck source=/dev/null
source "$HOME/.bashrc"

# build sources
(
    cd sbtc || exit
    # Build the package that we have to build first.
    cargo build --package emily

    # Build the repo.
    cargo build && cargo test
)
```

Then the npm build script `.generated-sources/emily/build.rs` needs to have the `npm` calls be `pnpm`.

This is actually all okay, the problem is that `cargo lambda` doesn't build at this point because it needs to install `zig` with npm and no matter what I do it says it isn't installed correctly. From what I understand isn't an issue on MacOS; does this script answer the questions of what's needed for the local build to work?

**Comment by AshtonStephens** [comment]
I ignored this checklist because I think it's overkill, if anyone has an issue they can make a GH ticket and we can trouble shoot that system.
