### ISSUE TITLE
sbtc-cli generates different stx address than clarinet

### ISSUE THREAD

**Issue by friedger** [stacks-network/sbtc#101]
Using the mnemonic defined in `romeo/asset-contracts/settings/Devnet.toml` for `sbtc generate-from mnemonic "...."` result in a different stx address

clarinet generates 
```
# stx_address: ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM
# btc_address: mqVnk6NPRdhntvfm4hh9vvjiRkFDUuSYsH
```
sbtc generates:
```
  "stacks_address": "ST24M0AD5N2QXBXC8HKFVZVYJQP4VFMA0VVYWN4WQ",
```

**Comment by stjepangolemac** [comment]
This might have something to do with the difference in key derivation paths between Bitcoin and Stacks addresses. Maybe we need to look into stacks.js and see how they do it, also why they do it.

**Comment by friedger** [comment]
[stacks.js](https://github.com/hirosystems/stacks.js/blob/b2a5f96fd24e8da7cb9b4e1cf4d7b654f6e5b00c/packages/wallet-sdk/src/derive.ts#L12) uses:
``` 
const DATA_DERIVATION_PATH = `m/888'/0'`;
const WALLET_CONFIG_PATH = `m/44/5757'/0'/1`;
const STX_DERIVATION_PATH = `m/44'/5757'/0'/0`;
```

**Comment by friedger** [comment]
stbc-cli does not use any derivation path

**Comment by stjepangolemac** [comment]
I'll need to figure out how to use derivation paths with bdk. Do you know anything about that?

**Comment by stjepangolemac** [comment]
Fixed in https://github.com/stacks-network/sbtc/issues/119
