### ISSUE TITLE
[sBTC DR] deployment on devnet

### ISSUE THREAD

**Issue by friedger** [stacks-network/sbtc#103]
Currently, the binary deploys the asset contract only. However, there is a dependency to the SIP10 trait. Therefore, the deployment to devnet when using clarinet integrate would fail.

There are two possible solutions:
1. Delegate deployment to clarinet (easy)
2. Deploy SIP10 trait as well

**Comment by stjepangolemac** [comment]
From the context of Romeo it does not care how the trait gets deployed. Its only goal is to deploy the asset contract. I'd suggest something like this:

1. Romeo loads up the contract and finds the place where the trait address is set
2. It replaces the address with the correct one that can be set up in the config or somewhere else (suggestions welcome)
3. It successfully deploys the contract

@friedger what do you think?

Also, who else should we ask for some feedback? Maybe @jo-tm?

**Comment by friedger** [comment]
Another, better idea: We can just remove the `imp-trait` statement.

**Comment by CAGS295** [comment]
In #95 there will be a step where you can explicitly set the initial state. It is very likely that the first thing I'm going to try is to assimilate deployment files into storage as the initial state. I would go with 1. if you can't drop the `imp-trait`.

**Comment by friedger** [comment]
It does not matter whether you add the `impl-trait` declaration or not as long as the contract implements the trait, that is has functions with the signature defined in the trait.

You can also have two traits with the same definitions and the contract implements both.
