### ISSUE TITLE
[Feature]: Implement signer metrics & exporter

### ISSUE THREAD

**Issue by cylewitruk** [stacks-network/sbtc#1049]
# Feature - Implement signer metrics & exporter

## 1. Description

@aldur brought up the desire to be able to collect real metrics from the signers into e.g. prometheus.

Some of the metrics mentioned were:

- Number of stacks blocks received
- Number of Bitcoin blocks received
- Signing rounds
- Number of times the signer has been a coordinator

And we can probably come up with some other interesting ones to throw in.

### 1.1 Context & Purpose

This would allow us to collect more quantifiable metrics without needing to rely on log-counting, and would help to increase observability and confidence in the mainnet release.

## 2. Technical Details:

I think we should try to use [OpenTelemetry](https://opentelemetry.io/) [metrics](https://docs.rs/opentelemetry/latest/opentelemetry/metrics/index.html) to stay agnostic if we can, which should be [directly supported by prometheus](https://prometheus.io/blog/2024/03/14/commitment-to-opentelemetry/). Unfortunately vector doesn't support OTLM metrics at the moment, only log and trace spans... :( 

My first thought was that we could use the `SignerState` to hold the metrics, but on second thought I think we should have a separate global static for this as not everything has access to a `Context`.

**Comment by djordon** [comment]
I'm a big fan of https://github.com/metrics-rs/metrics for instrumenting applications. It doesn't have an opentelemetry metrics exporter though.

**Comment by cylewitruk** [comment]
> I'm a big fan of https://github.com/metrics-rs/metrics for instrumenting applications. It doesn't have an opentelemetry metrics exporter though.

Cool, let's use that then, it has a prometheus scrape exporter so that'll be perfect 👍
