### ISSUE TITLE
[Bug]: sBTC token not SIP 10 compatible

### ISSUE THREAD

**Issue by friedger** [stacks-network/sbtc#1090]
SIP-10 requires to print memos provided in the transfer function. The sBTC token contract does not print the memo.

See https://github.com/stacksgov/sips/blob/main/sips/sip-010/sip-010-fungible-token-standard.md#transfer

**Comment by setzeus** [comment]
Already added here: https://github.com/stacks-network/sbtc/pull/1008

Just to confirm, does the print statement have to follow the format mentioned (using match) or is the following valid?

`(print {
	topic: "transfer",
	amount: amount,
	sender: sender,
	recipient: recipient,
	memo: memo
})`

**Comment by friedger** [comment]
The requirement is that the next event after ft transfer event is the memo.
