### ISSUE TITLE
[Feature]: Retrieve and Store sBTC Deposit Amount 

### ISSUE THREAD

**Issue by Jiloc** [stacks-network/sbtc#1100]
# Feature - Retrieve and Store sBTC Deposit Amount

## 1. Description

Currently, the `amount` field in `ScriptParameters` is hardcoded to `0` in the Emily `deposit.rs` handler. This prevents accurate reporting of the deposit amount in the bridge and other user-facing interfaces. The feature request aims to extract the correct deposit amount from the provided transaction data and store it appropriately in the system.

### 1.1 Context & Purpose
The hardcoded value was noted during development as a placeholder because the deposit amount is encoded in the original transaction, and Emily doesn't currently have access to it. This limitation impacts Emily's ability to provide accurate information for deposits.

## 2. Technical Details:
One. simple, possible solution could be to add the deposit amount to the request (`CreateDepositRequestBody`) and save it alongside the deposit request. Note that the amount will not be validated by Emily (nor will be used by the signers, that will keep using the original tx), but will just be stored for visualization purposes.

### 2.1 Acceptance Criteria:
   - [ ] Add the amount to the CreateDepositRequestBody.
   - [ ] Replace the hardcoded `amount: 0` value with the extracted deposit amount.

## 3. Related Issues and Pull Requests (optional):
- [Reference code with the hardcoded `amount: 0`](https://github.com/stacks-network/sbtc/blob/fdbf78481cbd28d420bab98dcd98725dc19bc8f8/emily/handler/src/api/handlers/deposit.rs#L295).

**Comment by djordon** [comment]
We decided to have Emily take the entire transaction hex, so we can get the amount from there. So this is no longer needed.
