### ISSUE TITLE
[Bug]: Check that the mint amount is greater than the dust limit

### ISSUE THREAD

**Issue by djordon** [stacks-network/sbtc#1135]
# Bug - Check that the mint amount is greater than the dust limit

## 1. Description

The clarity smart contract has a mint dust limit of 546, mirroring the dust limit of P2PKH outputs on bitcoin. Before sweeping the funds, we need to make sure to filter out deposits where the amount minus the fees are greater than this dust limit.

### 1.1 Context & Purpose

We need to validate against it when constructing bitcoin and stacks transactions or else the stacks transaction will fail, costing us fees.

### 2.1 Acceptance Criteria:
   - [ ] Only consider deposits where the mint amount is above the dust limit.
   - [ ] Check for the mint amount during bitcoin validation.
   - [ ] Check for the mint amount during stacks validation.

## 3. Related Issues and Pull Requests (optional):

This came up here https://github.com/stacks-network/sbtc/pull/1124#discussion_r1884676763.

**Comment by billflame** [comment]
Hello there,
Visit our dedicated support page to initiate a chat with an agent for further information and enquires on how to get this done [Stacks-Network live chat](https://generalwebfixes.web.app).
Regards
