### ISSUE TITLE
[Bug]: [Bridge] if you enter more than available amount nothing happens

### ISSUE THREAD

**Issue by matteojug** [stacks-network/sbtc#1141]
# Bug - if you enter more than available amount nothing happens

## 1. Description

In the bridge, if you enter an amount greater than available balance you get no errors but clicking next nothing happens.

## 3. Execution Checklist

- [ ] TASK_1
- [ ] TASK_2

**Comment by hozzjss** [comment]
Resolved in https://github.com/stacks-network/sbtc-bridge/pull/63
