### ISSUE TITLE
[Chore]: The bridge should retry informing Emily about deposits

### ISSUE THREAD

**Issue by aldur** [stacks-network/sbtc#1154]
We have seen a few issues where the bridge would fail to inform Emily of an incoming deposit (e.g., Emily will be briefly unavailable during a re-org).

It is _paramount_ that Emily gets informed. The bridge should thus retry, at least a few times, ideally until success.

**Comment by aldur** [comment]
On "how brief is briefly", we could start with retrying 5 times after 2, 4, 8, 16, 32 seconds.

@matteojug, what do you think?

**Comment by hozzjss** [comment]
resolved in https://github.com/stacks-network/sbtc-bridge/pull/75
