### ISSUE TITLE
[sBTC DR] binary can use the same tx several times

### ISSUE THREAD

**Issue by friedger** [stacks-network/sbtc#116]
We have a clarity tests that shows that the binary can use the same bitcoin tx serveral times to mint or burn. Can we trust the binary that it does not rerun the mint or burn flow several times? E.g. when restarting?

![image](https://github.com/stacks-network/sbtc/assets/1449049/8fe00cb5-cfda-4774-a1a0-e234db952e6b)

This is maybe a discussion: Should we add a registry of txs used for mint and burn?

**Comment by setzeus** [comment]
Something functionality similar to the registry contract we previously [had](https://github.com/Trust-Machines/stacks-sbtc/blob/main/sbtc-mini/contracts/sbtc-registry.clar)? Probably don't need a standalone file for now I'm suggines.

Would we want a single map to track *all* BTC transactions successfully submitted or should we split up into two maps, one that keeps track of deposit & withdrawal submitted BTC transactions?

**Comment by friedger** [comment]
I think one map for all btc tx would be enough, it could be a map from `buff` (txid) to `int` (amount) where `int` is the amount that was minted if positive or burnt if negative

**Comment by friedger** [comment]
Maybe we ignore it and move on...

**Comment by friedger** [comment]
We don't care because it is a centralized miner anyway.

**Comment by friedger** [comment]
Currently, I don't trust the binary and would like to see a safety net in clarity @setzeus
