### ISSUE TITLE
[Feature]: Bitcoin interface for the block observer

### ISSUE THREAD

**Issue by netrome** [stacks-network/sbtc#117]
# Feature - Bitcoin interface for the block observer

## 1. Description

Define a bitcoin interface for the block observer

### 1.1 Context & Purpose
To be able to support the block observer event loop, we need to define a bitcoin interface with the appropriate operations that is needed for the block observer to be able to function.

### 2.1 Acceptance Criteria:
   - [ ] We have a trait with the appropriate bounds and methods to support the block observers need to query the Bitcoin blockchain.

**Comment by djordon** [comment]
With https://github.com/stacks-network/sbtc/issues/759 we'll likely expand the interface a little, what was asked for here is done.
