### ISSUE TITLE
[Feature]: Use 'or_else' variants of 'or' function calls to improve performance

### ISSUE THREAD

**Issue by johnsaigle** [stacks-network/sbtc#1174]
# Feature - Use 'or_else' variants of 'or' function calls to improve performance

## Description

Use `unwrap_or_else` and `ok_or_else` which evaluate lazily instead of the simple `or` variants that evaluate eagerly. This should save some wasted computation in the happy path.

* https://doc.rust-lang.org/std/result/enum.Result.html#method.unwrap_or
* https://doc.rust-lang.org/std/option/enum.Option.html#method.ok_or

### Main
[signer/src/bitcoin/validation.rs:267](https://github.com/stacks-network/sbtc/blob/891677e7602f97b2e088e9940b2b4536ae9aad1b/signer/src/bitcoin/validation.rs#L267)
[signer/src/bitcoin/validation.rs:267](https://github.com/stacks-network/sbtc/blob/891677e7602f97b2e088e9940b2b4536ae9aad1b/signer/src/bitcoin/validation.rs#L276)

The `into_error()` function will always be called even when there is no error. This function in turn `Box`es a value. This allocation can be avoided if the 'else' variant is used. 

### Testing
[signer/src/testing/block_observer.rs:106](https://github.com/stacks-network/sbtc/blob/891677e7602f97b2e088e9940b2b4536ae9aad1b/signer/src/testing/block_observer.rs#L106)

The call to the BTC Rust library's `all_zeros` function call can be avoided in the happy path. I assume this also does an allocation of some kind so it might give you a small performance boost.

**Comment by djordon** [comment]
Good point, and makes perfect sense. Thanks for opening a ticket!
