### ISSUE TITLE
[Feature]: Stacks interface for the block observer

### ISSUE THREAD

**Issue by netrome** [stacks-network/sbtc#118]
# Feature - Stacks interface for the block observer

## 1. Description

Define a stacks interface for the block observer

### 1.1 Context & Purpose
To be able to support the block observer event loop, we need to define a stacks interface with the appropriate operations that is needed for the block observer to be able to function.

### 2.1 Acceptance Criteria:
   - [ ] We have a trait with the appropriate bounds and methods to support the block observers need to query the Stacks blockchain.

**Comment by djordon** [comment]
This might be done already, I'll double check to make sure.
