### ISSUE TITLE
[stacks-core] Correct credential generation

### ISSUE THREAD

**Issue by stjepangolemac** [stacks-network/sbtc#119]
At the moment the `sbtc-cli` created credentials that are usable for general sBTC testing. We've always had a discrepancy between generated credentials and those Leather (Hiro) wallet shows. The difference is in the custom derivation paths it uses which are different than Bitcoin ones.

We need to be able to generate the credentials using the derivation paths widely accepted in the Stacks ecosystem. This should probably be prioritized as @radicleart depends on this for his bridge work.

**Comment by friedger** [comment]
Is this a duplicate to #101 ?

**Comment by stjepangolemac** [comment]
Yep you're right. I'll close the other one.
