### ISSUE TITLE
Parallelize CI for the repo

### ISSUE THREAD

**Issue by stjepangolemac** [stacks-network/sbtc#136]
I've asked @AshtonStephens and it seems like this is possible. If there are no downsides it would speed up the CI considerably.

**Comment by jo-tm** [comment]
What takes some time for Rust is the Linter? -> 90 seconds
![image](https://github.com/stacks-network/sbtc/assets/30682875/224797a8-66d4-4d03-a7bf-3eba3ef564be)

**Comment by jo-tm** [comment]
Linter and Coverage in Rust can be Parallelized:
![image](https://github.com/stacks-network/sbtc/assets/30682875/3ad38159-42d4-4f2e-a6fb-80b9f75c2043)

**Comment by jo-tm** [comment]
is improving around 50% now 👍
![image](https://github.com/stacks-network/sbtc/assets/30682875/8c5e8167-39e2-452a-8329-30f163d9a744)

**Comment by stjepangolemac** [comment]
Nice, thank you!
