### ISSUE TITLE
Use asset.clar not in debug mode for devenv/testnet

### ISSUE THREAD

**Issue by friedger** [stacks-network/sbtc#142]
There is a DEBUG flag in `asset.clar` that should be false for devenv and testnet

**Comment by friedger** [comment]
@stjepangolemac The devnet, testnet and mainnet version should not have the whole debug section for performance. There should be two versions of the contract, one for unit tests, one for devnet, testnet and mainnet

**Comment by stjepangolemac** [comment]
I've made debug mode disabled in the current contract in the withdrawal flow PR / branch. I suppose we can close this one now. If you disagree feel free to reopen and discuss.

**Comment by friedger** [comment]
We need two versions of the contract: one for unit tests, one for deployment on devnet and testnet.
