### ISSUE TITLE
[sBTC DR] Use bitcoin merkle tree instead of stacks merkle tree

### ISSUE THREAD

**Issue by friedger** [stacks-network/sbtc#144]
The current implementation uses stacks merkle trees with tagged hashes using 0 (leaf) and 1 (path).
For bitcoin tx verification, we need merkle trees without tags.

**Comment by stjepangolemac** [comment]
What if we add merkle trees to stacks-core? I can give it a go on Monday if you agree.

**Comment by friedger** [comment]
rs_merkle requires fixed sized arrays and we have block.txdata of type Vec

**Comment by stjepangolemac** [comment]
That's not an issue as they can be converted, they're always of the same size. From looking at the documentation it seems like it accepts vectors also.

The thing we need to figure out is if the code that validates these proof uses stacks or bitcoin implementation for merkle trees.
