### ISSUE TITLE
[sBTC DR] Block Merkle Root & Witness Root Test Case

### ISSUE THREAD

**Issue by setzeus** [stacks-network/sbtc#146]
Generated merkle & witness trees for three blocks in testnet. 

Point of this issue is to provide @moodmosaic with generated trees for tests cases around merkle verification functionality (not entirely where sure these would live best so attaching a json here for @moodmosaic to place accordingly instead of opening a PR). 

https://gist.github.com/setzeus/469e747290961c03adb09fbeff2534f3

**Comment by friedger** [comment]
As a property of testN, I'd add sender address and receiver address and amount in sats. Then these test data can be used for property testing.

**Comment by friedger** [comment]
There is now a tool to generate and verify proofs: https://bridge.sbtc.tech/proofs?net=testnet
