### ISSUE TITLE
Draft SIP: sBTC

### ISSUE THREAD

**Issue by will-at-stacks** [stacks-network/sbtc#155]
## Description of the Task/Feature:
Prepare a draft SIP for sBTC Protocol & Asset

## Associated Working Group(s):
[    ] Stacks Blockchain
[ x ] sBTC
[    ] ClarityWASM
[    ] Clarity
[    ] Quality of Life

## Acceptance Criteria:
- Format of draft SIP conforms to standard outlined [here](https://github.com/stacksgov/sips/blob/main/sips/sip-000/sip-000-stacks-improvement-proposal-process.md#sip-format)   
- Reviewed for completeness by the following @obycode @AshtonStephens @jferrant @xoloki @setzeus @jcnelson @kantai @andrerserrano 

## Estimated Effort: 
[    ] XS (< 1 day)
[    ] S (< 1 day)
[    ] M (1-2 wks)
[ x ] L (2-4 wks)
[    ] XL (> 4 wks
[    ] XXL (~1 quarter)

## Requested Date of Completion: 
10-31-2023

## Assignee: 
@EmbeddedAndroid

**Comment by friedger** [comment]
See https://github.com/stacksgov/sips/pull/156
