### ISSUE TITLE
Romeo should pass the unreversed txid to asset contract

### ISSUE THREAD

**Issue by radicleart** [stacks-network/sbtc#164]
The deposit_txid parameter of this [stacks tx](https://explorer.hiro.so/txid/0x490c4393f08a13290deb49260ce60ce202bc8efa45ef760426a23553aa7c9b90?chain=testnet) is reversal of the actual [bitcoin txid](https://mempool.space/testnet/tx/01d8467b25e1d415bf53427d4db86fe001590b280b604204f794c5ecfc923ed3)

Romeo should pass the unreversed txid so app developers can use this value to lookup bitcoin transactions without worrying about first having to reverse the byte order.

Note the reason for reversing the txid is because the asset contract calls the clarity-bitcoin-mini to confirm mining of the transaction which requires the reversed txid. However clarity-bitcoin-mini has a method to compute the reversed txid.

The comments for method `verify-merkle-proof` in clarity-bitcoin-mini also need to be updated to make it clear it takes the unreversed txid as input.

#### Definition of done

Txids in contract function arguments should be shown in the same canonical format as in Bitcoin exporers.

**Comment by stjepangolemac** [comment]
@friedger what's the default way of representing bitcoin txids on the wire, reversed or not?

**Comment by friedger** [comment]
@stjepangolemac as the txid is shown in the stacks explorer it should be shown in the same way as in the bitcoin explorer for user to easy understand.

**Comment by stjepangolemac** [comment]
So if I've understood it correctly the only place where we can see the txid being reversed in comparison to the stacks and bitcoin explorers are `deposit/withdrawal-txid` fields. Can we reverse it in the contract so that arguments are clearer for an observer?

**Comment by radicleart** [comment]
The issue is that Romeo sends it reversed which means in the stacks explorer and in clarity events the txid will be reversed - this will confuse a lot of people because they will copy/paste the txid into eg mempool and see non existent transaction. e.g.

<img width="1092" alt="Screenshot 2023-09-25 at 12 03 09" src="https://github.com/stacks-network/sbtc/assets/4384929/55364dac-1e81-4fba-8d9e-94b69c1ce7eb">

**Comment by radicleart** [comment]
I beleive the Clarity-Bitcoin-Mini : was-txid-mined also reverses the txid - ie reverses the reversed  txid !

**Comment by friedger** [comment]
To clarify, clarity-bitcoin-mini expect the txid in the same style as shown in the explorers, that is in big endian.

**Comment by stjepangolemac** [comment]
Okay I've updated the description. I'll take this when the bulk of other Romeo work is done.

**Comment by friedger** [comment]
In devenv, I see that romeo sends the txid in the correct format. 

I have added another test to confirm that in branch 164-txid

**Comment by radicleart** [comment]
Can you post the proof data ? Maybe i can run the bridge locally on regtest and check it against the bridge proof data.

**Comment by stjepangolemac** [comment]
Seems like txids are passed correctly after all? To be honest, I'm a bit confused with all this.

**Comment by radicleart** [comment]
I've not been able to retest @stjepangolemac because of rate limit issues running romeo. 

The [mint here](https://explorer.hiro.so/txid/0x490c4393f08a13290deb49260ce60ce202bc8efa45ef760426a23553aa7c9b90?chain=testnet) was called by Romeo on testnet in response to this [deposit](https://mempool.space/testnet/tx/01d8467b25e1d415bf53427d4db86fe001590b280b604204f794c5ecfc923ed3) 

the deposit-txid printed in the explorer is reverse of the bitcoin txid ?
0xd33e92fcecc594f70442600b280b5901e06fb84d7d4253bf15d4e1257b46d801

deposit-txid gets passed to was-tx-mined as txid. Not sure whats going on but reproducing the test on testnet will help clarify.

**Comment by radicleart** [comment]
Retested this and correct big endian txid is being passed to stacks clarity contract.
