### ISSUE TITLE
[sBTC DR] clarity-bitcoin-mini errors with u7 when called with unreversed bitcoin txid

### ISSUE THREAD

**Issue by radicleart** [stacks-network/sbtc#166]
In scenario where Romeo reverses the txid, clarity-bitcoin-mini:was-txid-mined throws error u7 [see related issue](https://github.com/stacks-network/sbtc/issues/164)

However calling  clarity-bitcoin-mini:was-txid-mined directly with the same data but with the unreversed txid also throw error u7 (ERR-INVALID-MERKLE-PROOF).

**Comment by radicleart** [comment]
The issue is that Romeo sends it reversed which means in the stacks explorer and in clarity events the txid will be reversed - this will confuse a lot of people because they will copy/paste the txid into eg mempool and see non existent transaction. e.g. 

<img width="815" alt="Screenshot 2023-09-26 at 13 39 48" src="https://github.com/stacks-network/sbtc/assets/4384929/5d978dd9-38bf-4eca-b94a-a7476350315b">

**Comment by radicleart** [comment]
Added a tool for checking txid to bridge (will hide behind advanced setting soon).

WIP but right now the tool pulls block data and displays merkle tree and proof for any given tx and then calls the Clarity bitcoin contract with the proof data. 

The goal is to isolate the origin of the U7 error - in Romeo or in the Clarity.

**Comment by radicleart** [comment]
See this [mint tx](https://explorer.hiro.so/txid/0x490c4393f08a13290deb49260ce60ce202bc8efa45ef760426a23553aa7c9b90?chain=testnet) for example.

**Comment by radicleart** [comment]
Thanks to @setzeus / @friedger we managed to get an [independent check](https://bridge.sbtc.tech/proofs?net=testnet) on the merkle proof parameters passed from Romeo to clarity-bitcoin-mini via the asset contract.

Next step is to compare the proof passed from romeo for deposits.

**Comment by radicleart** [comment]
Header (romeo)
00600120d2119865b5b567cec541f80c7657e0d956cb5934e203ade332000000000000005fe61766d52c5452bfe45ffcf0536fe7f94a84c4a1c20f300e714c9385956b0364861165c0ff3f1911761e93 

Header (bridge)
00600120d2119865b5b567cec541f80c7657e0d956cb5934e203ade332000000000000005fe61766d52c5452bfe45ffcf0536fe7f94a84c4a1c20f300e714c9385956b0364861165c0ff3f1911761e93

Proofs (romeo)
268c873b99d12a8ea0c87e05de4ac98b16398217abc97f79b94bd9bea35a5ce6 a26c0adbdd5400d76e12dfc5412d08df244085f538fee7c5c5a2e419caf0450a 45cc4022c36723ff1e4f9ee1a1529b5ffff1cf1121f326145505f52ae6b6ea19 e6b607cb87927805a43058e0d5ddfd61249c40b622037a074ec3c76eb48a6416 cba219199a82ffedd0f4582b11e05e4940cf7873c655f4225e7a88e98d883479 c8409d8249608a85ce79705d7df877b12079dd6b28ad416b801844bfa9cf810a f5d5ea2d88e8f71b5e34256cc206c44e93258b301b8d94f5bed4f601377e6e36

Proofs (bridge)
d13fbfe1f20169cfa711dca363f35e46cb1c5e0bb35d40489d459b8f31baeb45 997442ee8c0e7f5864da8abe60e444efbb654d475b128f9cbe4afb73070170cd 4bc7c20a4def4d812a48c04d054f23e71a04f287e9bc27665edffe28f84f9e52 628a627c34406cfdc00bd2c6b5669752a214df5049d6cf343c128fb657fcad6a 7a4ac858f4a7037ac64e2518e3fb019a501806b0db9635020f3db10db3086882 68b73efeba1f17cfcdb6c7a5c921400d6eac1f9853fd20c1d8dfb9788b126459 f431f73ead8f01b0dda4dd2936013a0177dcec109b4891d36a2805a6f05d6721

**Comment by stjepangolemac** [comment]
So that means the way we calculate the proof in Romeo is wrong? @friedger were you able to confirm this to be working before or we never actually knew for sure?

**Comment by radicleart** [comment]
Confirmed in this [mint](https://explorer.hiro.so/txid/0x73c382acf066e12ba2c6a71b5a3d58dae0e5ecfa25c41640c8dae5a86bf98c72?chain=testnet) transaction the asset contract mints sBTC if passed correct merkle proof data.

**Comment by radicleart** [comment]
Successful [mint](https://explorer.hiro.so/txid/0x7facc5c4d5dab5b27c43772acb612fb77c852df26010e019823a7d4cb2ee6522?chain=testnet) on testnet corresponding to this [bitcoin tx](5dbc05258b3628e8468534cfd97b2961c10be04415ea45da8a5d54493bc572ab) sent from bridge application.

Merkle proof aggress with the that generated by the [bridge at /proofs](https://bridge.sbtc.tech/proofs?chain=testnet)

**Comment by radicleart** [comment]
Withdraw failed [see](https://explorer.hiro.so/txid/0x2fe0b42545b3cde3e6bc5de115c1e80aab734081e60e1abfdebc5f2c31534ebe?chain=testnet) :

```2023-10-04T09:25:01.491756Z  INFO update: romeo::state: Processing event=FulfillBroadcasted(WithdrawalInfo { txid: 2783bf9f1ca34797c58d14f9ce2a8518ccad410555db4569eee34d0b2c8bdba9, amount: 1000, source: Standard(StandardPrincipalData(ST32RAAXCQZ02HBQ9ZTCTZMF6EACRN4WP49ZPR479)), recipient: tb1qwe9ddxp6v32uef2v66j00vx6wxax5zat223tms, block_height: 2529382 }, aae2702e66bb20a806743cacef1f3d52c25fc0556acf3708eab5d782dcaa56dc)
2023-10-04T09:25:13.624250Z  INFO update: romeo::state: Processing event=StacksBlock(126835)
2023-10-04T09:25:13.624273Z  INFO spawn: romeo::system: Spawning task=FetchStacksBlock(126836)
2023-10-04T09:25:14.330975Z  INFO update: romeo::state: Processing event=StacksTransactionUpdate(2fe0b42545b3cde3e6bc5de115c1e80aab734081e60e1abfdebc5f2c31534ebe, Rejected)
thread 'main' panicked at 'Stacks transaction rejected: 2fe0b42545b3cde3e6bc5de115c1e80aab734081e60e1abfdebc5f2c31534ebe', romeo/src/state.rs:276:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace```

The bitcoin amount, recipient address and txid are correct. the stacks address is incorrect.


The merkle proof is different from the one [here](https://bridge.sbtc.tech/proofs?chain=testnet) the tree depth and nodes disagree.

**Comment by friedger** [comment]
The incorrect merkle proof is covered in #217 
Closing this one.
