### ISSUE TITLE
[sBTC DR] engine crashes when withdrawal fails on stacks

### ISSUE THREAD

**Issue by friedger** [stacks-network/sbtc#176]
This can happen when the user tries to withdraw more sbtc than the user owns.

Steps to reproduce:
1. launch devenv, deploy contracts, mint_btc.sh
2. deposit.sh
3. call withdraw.sh several times until the user ran out of sbtc
4. see crash

**Comment by CAGS295** [comment]
Is this related to some operations being infallible? #110

**Comment by friedger** [comment]
Deposit/mint could fall eg when the romeo engine ran out of STX. This request should eventually succeed. 

This issue is about withdrawal/burn that can fall because the user had not enough STX. The request should fail definitively.
