### ISSUE TITLE
[sBTC DR] bitcoin explorer not configured to show address details

### ISSUE THREAD

**Issue by friedger** [stacks-network/sbtc#177]
For any address, the bitcoin explorer shows 
![image](https://github.com/stacks-network/sbtc/assets/1449049/78eb862d-9352-4429-9f00-c6d049415998)

**Comment by friedger** [comment]
bitcoin explorer is removed in #242

**Comment by AshtonStephens** [comment]
@friedger lets keep this open for now because the bridge API might actually need the block explorer. Waiting on a response in #242 from @radicleart

**Comment by friedger** [comment]
Bitcoin explorer has been removed
