### ISSUE TITLE
Principal encoding for sBTC transactions

### ISSUE THREAD

**Issue by stjepangolemac** [stacks-network/sbtc#18]
Quoting @netrome's [comment](https://github.com/stacks-network/sbtc/pull/10#discussion_r1279009359):

> As we're moving beyond alpha, we want to have the encoding here be consistent with how a Clarity Principal is encoded according to SIP-005. This also ensures that the recipient can be a smart contract.

I've skimmed through the [SIP-005](https://github.com/stacksgov/sips/blob/main/sips/sip-005/sip-005-blocks-and-transactions.md) now but couldn't find the difference between our address encoding and it. Maybe you meant we need to be able to encode both contracts and ordinary addresses here?

I'll assign you on this one but feel free to remove yourself and just leave a comment.

**Comment by netrome** [comment]
Are we adding the `0x05` or `0x06` prefix indicating that the principal is a contract address already? 
![image](https://github.com/stacks-network/sbtc/assets/22524681/65fdb426-8aa8-4a97-99f8-f730a0707797)

Otherwise IMO that's the only difference.

**Comment by stjepangolemac** [comment]
Yeah we're not doing that at the moment. Thanks for the clarification.

**Comment by stjepangolemac** [comment]
Closed by https://github.com/stacks-network/sbtc/pull/41
