### ISSUE TITLE
stacks service fails to find a contract.

### ISSUE THREAD

**Issue by CAGS295** [stacks-network/sbtc#193]
sBTC service requests the deployment block height of an unexistent contract.

```2023-09-29T05:40:19.736443664Z thread 'tokio-runtime-worker' panicked at 'Could not get block height: cannot find contract by ID ST2GEN9CVCJNZPDH7Z7NPWRG6Z67GH3WWYAS4DGRA.sbtc-alpha-romeo-testing', romeo/src/system.rs:192:10```

We need to revisit the config.json for the sbtc service and the contract deployments for the stacks-node service.

**Comment by CAGS295** [comment]
@friedger, what deployer address and contract name would you expect in your romeo config file. `sbtc-alpha-romeo-testing` looks like a placeholder.

**Comment by friedger** [comment]
@CAGS295 you should deploy contracts with the utils script before launching romeo.

The name in the config must match the name in the default deployment plan. That is `asset`

In devenv this should be the default.

**Comment by friedger** [comment]
It looks like you are not using the correct mnemonic in docker/config.json. It should be the same as in settings/Devnet.toml
