### ISSUE TITLE
[Feature]: [Local Kubernetes setup for BTC Node and Miner]

### ISSUE THREAD

**Issue by SundarGowtham** [stacks-network/sbtc#198]
# Feature - [Local Kubernetes setup for BTC Node and Miner]

## 1. Description

This Issue contains the necessary components in K8s and Docker to get a Bitcoin Regtest node and a BTC miner running locally. We also introduce important setup, run, and testing commands for this local devnet. A Docker Compose version of the sBTC devnet exists in `devenv/local/docker-compose`, however, Kubernetes inherently has a better platform for orchestration and development. There will be some commonalities between the Dockerfiles in Docker Compose and K8s but the differences will also be discussed below.

### 1.1 Context & Purpose

We would like to run our sBTC Devnet using Minikube locally to have fine grained access and tuning for each component. The starting component of this devnet is the Bitcoin Regtest Node and a Miner attached to it.

### 2.1 Required Components:
Below are the necessary components for a Bitcoin Regtest Node and Miner :
- Docker build files for BTC Node & Miner
   - Move the logic of creating the `bitcoin.conf` file from the container to an `initContainer` functionality in K8s(discussed in 2.2)
- Kubernetes Deployment, Service, Secrets, and Namespace for BTC Node & Miner
- `utils/` folder which contains K8s utility scripts (port-forwarding etc.)
- `up.sh`, `build.sh`, `down.sh`, and `remove-minikube-containers.sh`
- `tests/devnet-liveness.sh` script which tests for BTC liveness and BTC mining ability
   - We can test for BTC Liveness by calling the `getblockcount` RPC call
   - We can test if the BTC Miner is working by actually mining a single block (`generatetoaddress` RPC call)

### 2.2 Considerations and Tradeoffs:

1) Why are we moving some build time logic like creating config files away from the container

Kubernetes does not work with build time configurations like Docker Compose does with the `build:` key. Which means anything which requires build time tuning as you will see in the creation of the bitcoin.conf in the Bitcoin container or the `config.toml` file in the Stacks/Nakamoto Signer containers will not be the same between K8s and Docker Compose. In Kubernetes, we will be addressing this by using `initContainers` and creating the files there.

2) Some of the Dockerfiles may look identical between Docker Compose and K8s

We may need to change the Dockerfiles later on in the K8s setup. If we start to notice that some of the Dockerfiles are not changing through our development, then we could move it to a `shared/docker-build` folder so that Docker Compose and K8s can use them.

### 2.3 Acceptance Criteria:
   - [ ] The test `tests/devnet-liveness.sh` returns with `0`

## 3. Related Issues and Pull Requests (optional):

#197

**Comment by djordon** [comment]
> Kubernetes does not work with build time configurations like Docker Compose does with the `build:` key. Which means anything which requires build time tuning as you will see in the creation of the bitcoin.conf in the Bitcoin container or the `config.toml` file in the Stacks/Nakamoto Signer containers will not be the same between K8s and Docker Compose.

I think we can just mount these config files using volumes like we would in docker compose. That should simplify things a bit.

**Comment by djordon** [comment]
Ah okay, let me see if I understand. Instead of directly changing each of the separate config files for each application (`bitcoin.conf` for `bitcoind` and so on for other applications), make the config files templates with variables that are filled in by environment variables during the `initContainers` run. Then if we want to change a parameter, we modify the environment variables in one kubernetes yaml file and things work the way we would expect. Is that right?

**Comment by SundarGowtham** [comment]
> Ah okay, let me see if I understand. Instead of directly changing each of the separate config files for each application (`bitcoin.conf` for `bitcoind` and so on for other applications), make the config files templates with variables that are filled in by environment variables during the `initContainers` run. Then if we want to change a parameter, we modify the environment variables in one kubernetes yaml file and things work the way we would expect. Is that right?

Yep precisely!
