### ISSUE TITLE
Introduce CI

### ISSUE THREAD

**Issue by stjepangolemac** [stacks-network/sbtc#20]
We need some sort of CI in this repo. I suggest these things:

- `cargo fmt`
- `cargo build`
- `cargo nextest run`
- `cargo clippy` (configured to reject on warnings too)
- `cargo doc`

Feel free to add more stuff. Tagging @sergey-shandar, @jferrant, @soju-drinker, and @netrome.

**Comment by AshtonStephens** [comment]
Yep.

**Comment by AshtonStephens** [comment]
I'll add CI here first then do it in stacks-sbtc repo. After I add the CI we may need to alter the PRs in review to pass.

Which directories hold the copy pasted code from stacks-blockchain? I'll have some of the CI skip those directories so we don't have redundant testing.

**Comment by stjepangolemac** [comment]
It's not yet decided but we probably won't have any copied code from `blockstack_lib` here.

Also, can we fit this into the CI: https://docs.rs/cargo-readme/latest/cargo_readme/

It generates package level readme files from doc comments. Simpler thing would be to check that those readmes are up to date, but it would be even better if the CI could generate them.

**Comment by netrome** [comment]
> Actually it might be the other way around https://gist.github.com/JakeHartnell/2c1fa387f185f5dc46c9429470a2e2be
> 
> Might be a better approach. @netrome what do you think?

Yeah I prefer using `include_str!()` and keep the README.md the source of truth. Automatic copying should be done as late as possible, and `include_str` pushes it to compilation :)

**Comment by stjepangolemac** [comment]
Yep I agree 👍

**Comment by AshtonStephens** [comment]
Initially I went the xtask route for this, but to get an early CI I'm going to copy what we've done for the https://github.com/Trust-Machines/stacks-sbtc. After we've finished our discussion in https://github.com/stacks-network/stacks-blockchain/issues/3844 I will likely add a script back.

**Comment by AshtonStephens** [comment]
Since there is now a CI as of https://github.com/stacks-network/sbtc/pull/40 I'm going to close this issue and open a new one around creating a more permanent one that follows the design principles that we want to use.
