### ISSUE TITLE
[Feature]: Block observer - extract deposit requests

### ISSUE THREAD

**Issue by netrome** [stacks-network/sbtc#203]
### Context
The block observer should as part of its operation extract any pending deposit requests from the bitcoin blocks it's processing and write the extracted requests to the signer database.

### Definition of done
The `extract_deposit_requests` method in the block observer is implemented and tested.

**Comment by djordon** [comment]
This one wasn't actually closed by https://github.com/stacks-network/sbtc/pull/315.
