### ISSUE TITLE
Prepare for sBTC Deployment onto the Default Testnet

### ISSUE THREAD

**Issue by AshtonStephens** [stacks-network/sbtc#209]
### Description

Document and prepare for sBTC deployment onto testnet during the week of Oct 9th.

### Context / Purpose

On October 16th and 18th the Stacks Foundation is going to host a hackathon in London and launch a testnet program which both require a usable sBTC release with a testnet deployment. In order to meet our promises we need to have a launch on Hiro's default testnet. 

### Steps

- [ ] Discuss with @stjepangolemac, @wileyj, and @kantai on the steps needed to get this functionality on testnet
- [ ] Document the required steps steps and identify the resources we need.

### Artifacts / Acceptance Criteria

- [ ] We have a written artifact outlining the steps and resources needed for sBTC release on testnet + agreement on that document by both @wileyj and @kantai (and ideally @stjepangolemac)

**Comment by radicleart** [comment]
Also [199](https://github.com/stacks-network/sbtc/pull/199#issuecomment-1742988042)

Be aware there may be a bitcoin testnet block storm that can prevent transactions confirming on Stacks testnet.

**Comment by AshtonStephens** [comment]
> See https://github.com/stacks-network/sbtc/issues/178 and https://github.com/stacks-network/sbtc/pull/194 

Yeah, I'm thinking that this may actually be very easy. Thank you clarinet team! 

> Be aware there may be a bitcoin testnet block storm that can prevent transactions confirming on Stacks testnet.

The testnet block storm would impact everyone though so from our position I'm not too worried. You're right, this storm is nuts. [mempool testnet block 2526084](https://mempool.space/testnet/block/0000000000000c7dc75dd419adba030860f40d77d8d0d789785c7878036653c7).

**Comment by AshtonStephens** [comment]
@setbern any update on this?

**Comment by setbern** [comment]
@AshtonStephens  https://docs.google.com/document/d/1WgmBKThoOrGAY2PFRYskNoqg-qLcR3jQBwHoT9Pf2Rw/edit

I think top priority is assigning a owner/working group for the testnet romeo engine. Since this requires the most hands on deployment.

**Comment by friedger** [comment]
> Deployment of the contract on clarinet is straightforward in a test net environment. 

Deployer needs to defined settings/Testnet.yaml with mnemonic defined earlier for Romeo engine.

**Comment by AshtonStephens** [comment]
This is done, the mnemonic is private but the asset contract is logged in the comments of https://github.com/stacks-network/sbtc/issues/209.
