### ISSUE TITLE
[Feature]: Block observer - extract update signer set transactions

### ISSUE THREAD

**Issue by netrome** [stacks-network/sbtc#209]
### Context
The block observer should as part of its operation extract any observed update signer set transactions from the stacks blocks it's processing and write the extracted requests to the signer database.

### Definition of done
The `extract_update_signer_set_transactions` method in the block observer is implemented and tested.

**Comment by djordon** [comment]
Is this ticket to extract `rotate-keys-wrapper` contract calls?

**Comment by netrome** [comment]
> @netrome is this ticket to extract `rotate-keys-wrapper` contract calls?

Yeah I believe so. That seems to be the contract call that sets the new signer set and the aggregate key. We should rename the internal function to match the new contract call name. We should probably rename this in the database as well.

**Comment by netrome** [comment]
The important aspect here is that the signer state model must be able to track when the signer set or the aggregate key has been updated.

**Comment by djordon** [comment]
> The important aspect here is that the signer state model must be able to track when the signer set or the aggregate key has been updated.

Okay cool. I think we can close this once https://github.com/stacks-network/sbtc/issues/210 is closes, since the `rotate-keys-wrapper` contract call updates the new signer set and sets the aggregate key.

**Comment by djordon** [comment]
The other one ticket was closed, closing this one as well.
