### ISSUE TITLE
Set up automated crates.io publishing on tags

### ISSUE THREAD

**Issue by stjepangolemac** [stacks-network/sbtc#21]
@AshtonStephens I'm tagging you for the automation, I'll make sure the repository fulfills all the prerequisites for publication.

https://doc.rust-lang.org/cargo/reference/publishing.html#publishing-on-cratesio

**Comment by stjepangolemac** [comment]
Here's the PR for requirements https://github.com/stacks-network/sbtc/pull/22

**Comment by stjepangolemac** [comment]
Requirements are in place now.

**Comment by AshtonStephens** [comment]
Do we want to start publishing right away, or is there a moment at which we'll be ready to start publishing?

**Comment by stjepangolemac** [comment]
I don't see why not. When we're sure the packages are in an usable state we can publish the 1.0 versions and continue from there.

**Comment by AshtonStephens** [comment]
Published pull request: https://github.com/stacks-network/sbtc/pull/52
