### ISSUE TITLE
[Feature]: Block observer writing stacks block

### ISSUE THREAD

**Issue by netrome** [stacks-network/sbtc#212]
### Context
The block observer currently only writes bitcoin blocks, and contains a placeholder function to write stacks blocks which we should implement.

### Definition of done
The `write_stacks_block` method in the block observer is implemented and tested.

**Comment by netrome** [comment]
@djordon hey I realize I missed that #251 doesn't implement the `write_stacks_block` function in the block observer - although it does all the heavy lifting for the postgresql storage, so reopening this so we can do a follow-up PR to actually implement this in the block observer.

**Comment by djordon** [comment]
Oh right, good call. Should be easy to add in.

**Comment by netrome** [comment]
> Oh right, good call. Should be easy to add in.

Yeah, and if it gets too nitty with the in-memory implementation and unit test we could push that as a follow-up.
