### ISSUE TITLE
[sBTC DR] Incorrect merkle proof for block with 11 txs

### ISSUE THREAD

**Issue by friedger** [stacks-network/sbtc#217]
### Expected Behavior
Merkle proof should be the same as on https://bridge.sbtc.tech/proofs?net=testnet

### Actual Behavior
The last leave in the merkle proof is different

### Steps to Reproduce

Run unit test in https://github.com/stacks-network/sbtc/pull/218

**Comment by friedger** [comment]
rs_merkle does not duplicate the last element if the layer has an odd number of elements. Instead it returns the unhashed last element.

**Comment by jcnelson** [comment]
Fulfilled in https://github.com/stacks-network/sbtc/pull/218/commits/1570110e6c198380da48bda0295bdf337d8201cc
