### ISSUE TITLE
[sBTC DR] devenv: sbtc down and up script do not bring sbtc back into a good state

### ISSUE THREAD

**Issue by friedger** [stacks-network/sbtc#226]
### Expected Behavior
After bringing up the devenv, I can cd in `sbtc` and call `./down.sh` and `./up.sh` to restart the romeo engine.

### Actual Behavior
Calling `./down.sh` and then `./up.sh`, results in  
```
Error response from daemon: Conflict. The container name "/sbtc" is already in use by container "0372471555e0f7149e6ad168ee175ebecc01894f3523e94bc56f4fbcda082e81". You have to remove (or rename) that container to be able to reuse that name.
```

After removing the container manually and calling `./up.sh` again, sbtc reports a panic
``` 
thread 'main' panicked at 'Failed to instantiate bitcoin client: Electrum client error: failed to lookup address information: Try again', /romeo/romeo/src/system.rs:45:10
``` 

### Steps to Reproduce
```
./up.sh
cd sbtc
./down.sh
./up.sh
```

**Comment by friedger** [comment]
`docker compose down [service]` is not available in version 20, the latest of the docker-ce on ubuntu.

Use `docker compose rm -v -s [service]` instead.

**Comment by friedger** [comment]
I still see the issue about "Electrum client error: failed to lookup address information" when running from main

**Comment by AshtonStephens** [comment]
@friedger is it in progress because you're looking at is or am I supposed to be looking at it? It's still  assigned to me

**Comment by friedger** [comment]
What shall we do with it? Can you confirm or not?

**Comment by AshtonStephens** [comment]
I'm getting the same thing until I try @EmbeddedAndroid's workaround.

> ```
> ./up.sh
> docker compose down sbtc
> docker compose up sbtc -d
> ```

Is this ticket now to update the `up.sh` and `down.sh` scripts?

**Comment by AshtonStephens** [comment]
Though, do we expect the `./down.sh` and `./up.sh` scripts to work when we launch with the big compose? Those are two very separate things in my mind

**Comment by AshtonStephens** [comment]
@EmbeddedAndroid @friedger @CAGS295 what's the main benefit of giving each of these their own "up" and "down" scripts? I think it would be safer to assume people only use the big docker-compose and if they want to do individual containers they can do the `docker compose up sbtc -d` or `docker compose up electrs -d` from within the `devenv` directory themselves.

I think having all these scripts separately opens a lot of opportunity for confusion and edge cases we need to handle.

**Comment by friedger** [comment]
While developing romeo engine, it is still useful, to do testing just by restarting the engine.

**Comment by friedger** [comment]
Solution:
stop sbtc:
Using `docker rm -f -s sbtc`

start sbtc:
Using ./up.sh in sbtc didn't work for me.
Using ./up.sh in devenv works

**Comment by friedger** [comment]
@AshtonStephens Let's do it in sbtc-docs.
