### ISSUE TITLE
sbtc: automatically deploy contracts

### ISSUE THREAD

**Issue by EmbeddedAndroid** [stacks-network/sbtc#231]
### Description

Now that https://github.com/stacks-network/sbtc/pull/173 has been merged, it would be ideal to have the sbtc container, deploy the contract automatically.

### Context

It will help new users if we can automate as much setup as possible, and reduce the risk of a bad experience because of complexity.

### Expected Approach

Leverage the setup from what @CAGS295 has done on the integration test container - https://github.com/stacks-network/sbtc/pull/215/files#diff-56bb3d9e8d0e342d456dd54468938fb905f8bea8793ddf7d3393d04a15c28661R9-R25

### Acceptance Criteria

- [ ] PR adds the feature 
- [ ] PR is reviewed and merged
- [ ] run ./up.sh, wait and then send deposit and withdrawal request

**Comment by janniks** [comment]
Will a while-sleep loop in a docker entrypoint as linked above, wait until the loop is done before it starts the dependant docker-compose services?

**Comment by CAGS295** [comment]
I have found that the script in the link is very effective. Try the following.
Wait for stacks-node rpc to be up. Loop sleep until stacks height is at least two. Use clarinet deployments to submit the contracts.

**Comment by janniks** [comment]
Cool thanks, I was using a docker compose healthcheck to wait and see when the stacks api /info works.

**Comment by CAGS295** [comment]
That could work, too. Do you have a snip?

**Comment by CAGS295** [comment]
Would a utils/script be used for deployments instead? I've been using this as an entry point for integration tests.
```bash
echo "Waiting on Stacks API $API_URL"
while ! curl -s $API_URL >/dev/null; do
    sleep 1
done

DEV_READY_HEIGHT=205

# bitcoind get info
echo "Waiting on burn block height $DEV_READY_HEIGHT"
while [ "$(curl -s $API_URL | jq '.burn_block_height')" -lt $DEV_READY_HEIGHT ]; do
    sleep 2
done

#stacks ready to take contracts
STACKS_HEIGHT=2
echo "Waiting on Stacks height $STACKS_HEIGHT"
while [ "$(curl -s $API_URL | jq '.stacks_tip_height')" -lt $STACKS_HEIGHT ]; do
    sleep 2
done

# any other service checks

# push contracts
cd romeo/asset-contract
sed -i "s/localhost:20443/$STACKS:20443/" deployments/default.devnet-plan.yaml
sed -i "s/localhost:18443/$BITCOIN:18443/" deployments/default.devnet-plan.yaml
clarinet deployments apply --no-dashboard -d -p deployments/default.devnet-plan.yaml
cd -
```

**Comment by friedger** [comment]
We have deploy_contracts which could include this in there.

**Comment by AshtonStephens** [comment]
@CAGS295 could you take this on?

**Comment by CAGS295** [comment]
> One thing to note here is that if we deploy contracts immediately Romeo will always process almost all blocks when started up. When working on it there are valid reasons to delay the contract deployment for later so when the environment is tweaked we can only let Romeo process a few blocks. That makes debugging easier.
> 
> This is a nitpick and I don't mind this being automated for now. After the hackaton we can reconsider if needed.

Can you expand on this? What is your perfect scenario?

**Comment by stjepangolemac** [comment]
For me as someone who works on Romeo perfect scenario is devenv being spun up and not modified in any way. That means no premining, no contract deployments, etc. That might change as I switch to work on something else.

I guess the idea that's been in my mind for a couple of days now is that we might want to separate these two things:

1. Setting up a pristine devenv to do with it whatever we need
2. Do some initial setup for some kind of work (in my case romeo dev work)

I think these should be separate as in separate scripts.

**Comment by friedger** [comment]
Let's create a script `up-pure.sh`
