### ISSUE TITLE
Romeo does not call mint in response to bitcoin testnet deposit.

### ISSUE THREAD

**Issue by radicleart** [stacks-network/sbtc#255]
### Expected Behaviour

Romeo initiates a mint on the testnet asset contract in response to deposit transaction on bitcoin testnet

### Actual Behaviour

Romeo fails to process the deposit bitcoin testnet transaction

### Steps to Reproduce

1. Sync with /sbtc main
2. cargo install --path romeo
3. cd ../romeo-demo
4. sbtc generate-from "mnemonic" >> creds.json
5. use this mnemomic to deploy the asset and clarity-bitcoin contracts to testnet
6. run Bitcoin testnet locally and enter connection string
7. RUST_LOG=romeo=trace romeo -c config.json

Note: may need own stacks node or a Hiro api key for the Hiro testnet stacks node.

### Sample Config.json

```
{
  "stacks_network": "testnet",
  "bitcoin_network": "testnet",
  "mnemonic": ".-- your mnemomic --",
  "state_directory": "./state",
  "bitcoin_node_url": "http://devnet:devnet@localhost:18332",
  "electrum_node_url": "ssl://blockstream.info:993",
  "stacks_node_url": "your api testnet stack node",
  "contract_name": "asset-1"
}
```

**Comment by stjepangolemac** [comment]
I've not been able to reproduce this on devnet.

There are 2 approaches I can / will take to try to debug this:

1. Looking into all the changes since last week when this was working
2. Running testnet romeo while pointing to the stacks testnet bitcoin node with rpc access

**Comment by friedger** [comment]
The problem is that the public key is wrongly set by the engine. The deposit was created using the information from the asset contract. Therefore, it was filtered out due to the wrong sbtc wallet address.
