### ISSUE TITLE
[Feature]: Transaction signer signing stacks transactions

### ISSUE THREAD

**Issue by netrome** [stacks-network/sbtc#255]
When the transaction signer receives a `StacksTransactionSignRequest` message, it should validate the request and if valid return an appropriate signature for the request.

### Definition of done
The transaction signer can respond to `StacksTransactionSignRequest` messages with a valid signature.

**Comment by djordon** [comment]
Signing a stacks transaction requires each signer to validate the stacks transaction, and that is blocked on https://github.com/stacks-network/sbtc/issues/426.
