### ISSUE TITLE
CORS error when trying to call devenv Mempool API

### ISSUE THREAD

**Issue by kenrogers** [stacks-network/sbtc#258]
### Expected Behavior

When calling devenv mempool API to fetch UTXOs, the UTXO set should be successfully returned

### Actual Behavior

Attempting to fetch UTXOs from devenv mempool API results in a CORS error

### Steps to Reproduce

1. Get devenv up and running with deposits processing successfully
2. Clone https://github.com/kenrogers/lagoon
3. Install everything with `npm install` and run with `npm run dev`
4. Connect wallet
5. Visit deposit page and initiate a deposit (btc address is hardcoded based on devenv address for now)

### Screenshots or Videos
<img width="467" alt="image" src="https://github.com/stacks-network/sbtc/assets/7418051/b5e0b946-7808-408a-8507-aa9a814ca3c7">

**Comment by friedger** [comment]
Workaround: Install enable cors plugin, eg "Allow CORS: Access-Control-Allow-Origin"

**Comment by friedger** [comment]
Fixed by https://github.com/stacks-network/sbtc/pull/260

**Comment by friedger** [comment]
Fixed by #260
