### ISSUE TITLE
Bug: mint on testnet fails due to btc block not yet processed

### ISSUE THREAD

**Issue by radicleart** [stacks-network/sbtc#261]
### Expected Behavior

Mint - in response to btc deposit - succeeds.

### Actual Behavior

Mint fails with error u6 (ERR-HEADER-HEIGHT-MISMATCH)

See [mint tx](https://explorer.hiro.so/txid/0x0b4d7fcebffe0dddd45825c77a5d428c2c81a63092e3d9a6f0d8ac0104840068?chain=testnet)

### Steps to Reproduce

1. run Romeo on testnet
2. send deposit using bridge or sbtc-cli

**Comment by friedger** [comment]
Did you deploy the `-deploy` contract in testnet deployment plan?

**Comment by radicleart** [comment]
Debug = false

See https://explorer.hiro.so/txid/0x53fa79edb8f86abc2e20421d289fa951deb624d9e11328d92f1cd437ef92df97?chain=testnet

**Comment by radicleart** [comment]
What if we increase number of confirmations required on bitcoin before minting/burning currently its 1 ?

**Comment by AshtonStephens** [comment]
@radicleart I'm going to implement this by allowing the mint to fail when there's not enough information and performing a retry later in the state machine.

Do you have a clear idea of how I might test this outside of Testnet?

**Comment by stjepangolemac** [comment]
Some ideas:

- Either introduce new events for mint / burn failure or extend existing ones
- When one of them fails reset its state in the same way it was before the first try, that way it does it again on next block
