### ISSUE TITLE
[sBTC DR] Invariant tests failing with the latest from main

### ISSUE THREAD

**Issue by moodmosaic** [stacks-network/sbtc#263]
### Expected Behavior

Invariant tests introduced in #152 should pass.

### Actual Behavior

Invariant tests fail as per the image below.

### Steps to Reproduce

Make sure you have the latest from `main` then:

```
cd romeo/asset-contract
clarinet test tests/asset_test.ts
```

### Screenshots or Videos

![image](https://github.com/stacks-network/sbtc/assets/287532/a1015a2f-650f-4af0-acf1-8e3b8d337b2f)

**Comment by moodmosaic** [comment]
Invariant tests should be part of the GitHub Actions build.

**Comment by friedger** [comment]
@moodmosaic Could you update the test using the clarinet-sdk? Then it would be covered by vitest.

This issue should be solved by adopting the invariant. The new property is that each btc tx can only be used for one mint or burn tx.
