### ISSUE TITLE
[Feature]: Add integration test scaffolding for deploying smart contracts

### ISSUE THREAD

**Issue by djordon** [stacks-network/sbtc#263]
# Feature - Add integration test scaffolding for deploying smart contracts

### 1.1 Context & Purpose

Signing a stacks transaction is kind-of-complicated. Once we have the mechanism for easily signing stacks transactions, we should add test code for deploying the sBTC smart contracts and making a contract call. This ticket is for deploying the smart contracts during the integration test. Because of the complexities of getting Nakamoto running, these integration tests do not need to run in CI (it's not that hard, it just takes a bit of time).

### 2.1 Acceptance Criteria:
   - [ ] Add code for deploying the smart contract locally.

## 3. Related Issues and Pull Requests (optional):

Follow on work after https://github.com/stacks-network/sbtc/issues/262.

**Comment by netrome** [comment]
I don't think we'll need to be able to deploy smart contracts for v0, just being able to sign contract calls should be enough afaik. Though it should be basically the same complexity though.

**Comment by djordon** [comment]
> I don't think we'll need to be able to deploy smart contracts for v0, just being able to sign contract calls should be enough afaik. Though it should be very similar.

Oh I was referring to deploying the smart contract in order to run the integration test, not for production use.

**Comment by djordon** [comment]
I updated the language to better reflect what I meant.

**Comment by netrome** [comment]
Oh nice, thank you for clarifying!
