### ISSUE TITLE
[sBTC DR] Withdraw on testnet via sbtc bridge fails

### ISSUE THREAD

**Issue by radicleart** [stacks-network/sbtc#266]
### Expected Behavior

A withdraw leads to successful burn operation on the sBTC contract

### Actual Behaviour

The burn [fails, see](https://explorer.hiro.so/txid/0x8a43b00c257f099c7791bd77ec88f09d3774368bd4713df007cf157da53e755c?chain=testnet) because the stacks address recovered from the users signature is different from the address they signed with. This leads to the contract trying to burn from an address with zero balance which fails in `ft-burn?` wth error U1.

### Steps to Reproduce

1. Initiate a withdraw via the [bridge](https://bridge.sbtc.tech) 
2. Ensure Romeo is connected and running
3. Monitor the stacks explorer for the burn transaction

### Notes

1. This is probably a bug in the bridge signing code - raising here for visibility
2. should be easy to check this by sending an sbct-cli withdraw to the same peg wallet.

**Comment by friedger** [comment]
I can confirm this when using lagoon withdrawal together with Hiro Wallet.  Looks like related to the sbtc sdk.

//cc @janniks

**Comment by friedger** [comment]
The tool by @radicleart shows sbtc owner `ST26DPVMSN4JN55Q7R5TZDWH3S4HSH348KVRF4A6`
![image](https://github.com/stacks-network/sbtc/assets/1449049/5db729ee-986a-43f4-85cc-eb67c466a78d)

Lagoon/Leather Wallet shows `STQA8RK9TFS3GP9AF6XGHDN77V12R63TKY96PPD2` (https://explorer.hiro.so/txid/0x7196a2599393f3ffeca1762ad6546c7766cbe7a388fdc933e54733283a7c05c9?chain=testnet) 

Expected was `ST1ZA396YZ6T06JRCVKGQ115QFHC9TQNR1C32201C`

**Comment by friedger** [comment]
Withdrawal with sbtc works as expected.

**Comment by janniks** [comment]
Not sure I follow. Does this need changes on the stacksjs sbtc package?

**Comment by friedger** [comment]
Maybe @kenrogers and I used the sbtc package incorrectly. In Lagoon, I get a wrong stx address.

**Comment by radicleart** [comment]
> testnet

as things stand there's a difference on testnet between the bridge code and the sbtc-cli in building the signature. I'm full steam tracking it down.

**Comment by janniks** [comment]
Hmm, so the address returned by the signature recovery / public-key? That part is handled by the Leather wallet in Lagoon.

or the way the passed stacksAddress is encoded into the btc transaction data?

**Comment by janniks** [comment]
@radicleart lmk how I can help, I made some alterations to the code until it matched the CLI (in most cases) and to get devenv to work

**Comment by radicleart** [comment]
i need help adding debugging to the cli so i can compare the pre signed message with that on the bridge. at least this what i'm trying but tripping on other issues..

**Comment by janniks** [comment]
Maybe this helps: https://github.com/hirosystems/stacks.js/commit/7c08244deee8b817bc65a44a8b84dead63d7be11#diff-6c652a1e7b05ebcc2abd8233527deb5382e0350731537477ec516a6e49cea6ad 
<img width="475" alt="Screenshot 2023-10-12 at 22 20 47" src="https://github.com/stacks-network/sbtc/assets/6362150/ebc22b6e-37dc-4883-8c07-2783e775952b">

Assuming I'm doing it correctly, but this was also from on older sbtc-lib time, so you might have changed some of these already.

**Comment by radicleart** [comment]
@janniks i'm reversing the recovery bytes here - maybe you can sanity check is the same ?

```
export async function signMessage(callback:any, message:string) {
	await openSignatureRequestPopup({
		message,
		network: getStacksNetwork(), // for mainnet, `new StacksMainnet()`
		appDetails: appDetails(),
		onFinish({ publicKey, signature }) {
			let newSig = signature.substring(0, signature.length - 2);
			const recByte = signature.substring(signature.length - 2);
			newSig = recByte + newSig
			const verified1 = verifyMessageSignature({ signature: newSig, message, publicKey });
			if (!verified1) throw new Error('verifyMessageSignature - signature is not valid')
			callback({ publicKey, signature: newSig }, message);
		}
	});
}
```

**Comment by radicleart** [comment]
Where do you add the 'length of data' byte ?

**Comment by janniks** [comment]
Yeah that looks the same.
Maybe I removed it, might have not been in the cli output when I was comparing 🤔
Where is the reference spec for this?

**Comment by janniks** [comment]
https://github.com/stacks-network/sbtc/blob/937456c334d9681606aaf9e769c44563fece9102/sbtc-core/src/operations/op_return/withdrawal_request.rs#L378 Maybe the rust parsing isn’t looking for a length-prefix. Can’t tell right now (I’m moving and don’t have my laptop) 🙃

**Comment by janniks** [comment]
I could have a moment tomorrow afternoon to compare the CLI bytes to the bridge-lib.

**Comment by radicleart** [comment]
I just had a successful withdraw through [bridge](https://explorer.hiro.so/txid/0x516ac1cba451d919ace4a939222b28fcaa756c8a1ee3c5c059e553e50a381d8e?chain=testnet)

not sure what going on here. I made one change, switched encoding the amount to use Miller lib....

```
	///const amountBuf = amountToBigUint64(amount, 8);
	const amountBytes = P.U64BE.encode(BigInt(amount));
```

i'll send a few more to see if this is consistent.

**Comment by radicleart** [comment]
Investigated this morning with Friedger and Stjepan and found the difference between the bridge and romeo is in how the message to be signed is handled - either as an array of bytes or os a hex encoded string. Treating the message to be signed as a hex string in both systems resolves the issue.

**Comment by janniks** [comment]
Got it 🙏🏻
Is / will romeo be changed? (Just checking if Stacksjs changes are needed)

**Comment by friedger** [comment]
@janniks romeo and sbtc js changed

**Comment by radicleart** [comment]
Yes - PR and branch here origin/266-change-message-format

**Comment by janniks** [comment]
Cool, thx I'll update as well as soon as I can. 🙏🏻

I wonder why withdraw worked for me on devenv 🤔

**Comment by radicleart** [comment]
@janniks - this is what we came up with - given the user has to sign a string regardless we made it a nice message.

See..

https://github.com/stacks-network/sbtc-bridge-api/blob/d14d050e7077ec852938a146bfceec5bd51b7c4d/sbtc-bridge-lib/src/payload_utils.ts#L334

**Comment by radicleart** [comment]
It worked on deven because both systems bridge/romeo were happy with encoding and decoding the message data. but they disagreed on how the message to be signed was encoded - as hex string or as bytes. They both treat it as string now !

**Comment by janniks** [comment]
Perfect, yeah a nice message is important. Thanks 🙏🏻

In future updates structured data might be cool as well, or some form of nonce/similar to avoid replays

**Comment by friedger** [comment]
I created an issue for structured data: https://github.com/stacks-network/sbtc/issues/286

**Comment by janniks** [comment]
Will update sbtc npm package tomorrow, OOO today
