### ISSUE TITLE
Incorrect romeo magic-bytes on withdraw

### ISSUE THREAD

**Issue by janniks** [stacks-network/sbtc#275]
_Potential bug report:_

Is it possible that sbtc romeo uses the testnet magicbyte for regtest (only for WITHDRAW, as far as I can tell.)
Maybe this is already fixed, I don't have the time to check the code myself right now, but wanted to mention it.

e.g. stacks.js test for withdraw needed to change this to make it go through on devenv:
https://github.com/hirosystems/stacks.js/blob/9171937ba5497e7ce3d660625621844600bb7b52/packages/sbtc/tests/withdraw.test.ts#L41

**Comment by friedger** [comment]
When using the cli, have you provided the network as `--network regtest` like here: https://github.com/stacks-network/sbtc/blob/f4130c63ec5680921617ac4b910d72ffb4072eb5/devenv/utils/withdraw.sh#L23?

The magic bytes are specified at https://github.com/stacks-network/sbtc/blob/5bd340f4a5d9285ea67e738d02e3976f11fb4dd0/sbtc-core/src/operations/mod.rs#L43

**Comment by janniks** [comment]
Ah right, I missed that. It worked without for deposit so I assumed I don’t need the flag. 🤔 Will compare again

**Comment by janniks** [comment]
Yep, turns out I provided the arg (using the utils script). But the sbtc-cli doesn't use the network arg for magic bytes for the withdraw tx, it rather uses the `broadcaster_bitcoin_private_key` (generated from a WIF string, so it will use testnet magic bytes) https://github.com/stacks-network/sbtc/blob/5dbcc260cd040250d501f9f150d1274c0552198a/sbtc-cli/src/commands/withdraw.rs#L87-L95

I feel the withdraw behavior should match the deposit behavior (which uses the CLI arg for the magic bytes).

---

> Also could someone point me to the "listening" code of sbtc, which waits for valid transactions, with the relevant magic bytes?

**Comment by friedger** [comment]
> Also could someone point me to the "listening" code of sbtc, which waits for valid transactions, with the relevant magic bytes?

@janniks Here happens the parsing of the op_return:

https://github.com/stacks-network/sbtc/blob/ebdcc7bc44aac6628bff8c9b8b5924f0589c0be7/sbtc-core/src/operations/op_return/deposit.rs#L147
