### ISSUE TITLE
[Feature]: Remove risk of over-fetching pending withdraw requests

### ISSUE THREAD

**Issue by netrome** [stacks-network/sbtc#277]
### Context
In #275, the initial postgresql query for fetching pending withdraw requests was defined. It works analogous to the in-memory implementation, which iteratively fetches stacks blocks until it encounters a stacks block confirmed by the first bitcoin block outside of the context window.

The problem with this approach is that if that particular bitcoin block doesn't confirm any stacks block on the canonical stacks chain, the algorithm will instead fetch all withdraw requests on the canonical chain.

### Definition of done
The withdraw request fetching query is improved so that it cannot over-fetch withdraw requests.

**Comment by djordon** [comment]
So I think what we're doing currently is actually correct. We just need to wait 6 bitcoin blocks, I don't think that we care if those blocks have anything to do with stacks blocks.

Let me know if you disagree. cc @hstove
