### ISSUE TITLE
Use sBTC wallet over peg wallet or dkg wallet

### ISSUE THREAD

**Issue by friedger** [stacks-network/sbtc#278]
### Expected Behavior
All developer facing code should use "sbtc wallet" in favor of "peg wallet" or "dkg wallet"

### Actual Behavior

There is mixed use of the three terms.
E.g. parameters of sbtc-cli use dkg-wallet for deposit and peg-wallet for withdrawal.

### Steps to Reproduce
Inspect code of sbtc-cli argument parsing, e.g. https://github.com/stacks-network/sbtc/blob/937456c334d9681606aaf9e769c44563fece9102/sbtc-cli/src/commands/withdraw.rs#L53

See also #274

**Comment by stjepangolemac** [comment]
I completely agree. I can change the occurences in this repo. @radicleart can you make sure your codebases also follow this? It's quite possible they already do.
