### ISSUE TITLE
[Feature]: Add Emily Primitives as Schemas to OpenAPI Template.

### ISSUE THREAD

**Issue by AshtonStephens** [stacks-network/sbtc#283]
# Feature - Add Emily Primitives as Schemas to OpenAPI Template.

## 1. Description

`utoipa` doesn't automatically pick up type aliases as schemas, this ticket is to figure out how to make it do that.

### 1.1 Context & Purpose

> TODO

## 2. Technical Details:

> TODO

### 2.1 Acceptance Criteria:
   - [ ] Criterion 1
   - [ ] Criterion 2
   - [ ] Criterion 3

**Comment by djordon** [comment]
Hmm, maybe with the newtype pattern?
