### ISSUE TITLE
[Feature]: Validate message to sign in transaction signer

### ISSUE THREAD

**Issue by netrome** [stacks-network/sbtc#296]
### Context
In #294, support for participating in WSTS signing rounds was implemented for the transaction signer. However, in this implementation, the transaction signer happily signs any message received from the coordinator. To ensure the signer doesn't sign any malicious message, it should ensure that the requested message is indeed the appropriate sighash for the given transaction.

### Definition of done
The transaction signer only participates in signing rounds for valid messages.

**Comment by djordon** [comment]
This ticket, https://github.com/stacks-network/sbtc/issues/578, adds more details.
