### ISSUE TITLE
Documentation - go wild on doc comments

### ISSUE THREAD

**Issue by stjepangolemac** [stacks-network/sbtc#3]
Let's try to make the crates from this workspace documented in the best way possible.

Here are some crates with very good documentation:

- https://docs.rs/rkyv/latest/rkyv/
- https://docs.rs/glommio/latest/glommio/
- https://docs.rs/clap/latest/clap/
- https://docs.rs/axum/latest/axum/

**Comment by stjepangolemac** [comment]
I've extended the description to emphasize that we need this for `stacks-core` and `sbtc-core`. I'd classify this as low priority but good to have.

**Comment by ldiego08** [comment]
@stjepangolemac I'd like to help with this one, if that's okay. Is this referring to docs on all mods and fns? If so, should only pub fns be documented?

**Comment by diwakergupta** [comment]
> @stjepangolemac I'd like to help with this one, if that's okay. Is this referring to docs on all mods and fns? If so, should only pub fns be documented?

cc/ @AshtonStephens
