### ISSUE TITLE
sBTC bitcoin transaction construction and broadcasting

### ISSUE THREAD

**Issue by netrome** [stacks-network/sbtc#31]
We need the SDK to support constructing, broadcasting and parsing sBTC bitcoin transactions. The priority for 0.1 is to support commit-reveal transactions for deposits and OP_RETURN fulfillments.

The SDK should expose functions capable of:

1. Creating a deposit commit transaction
2. Creating a deposit reveal transaction, consuming a deposit commit UTXO. Note, this function will need to take a representation of the script used in the deposit commit transaction as input in order to be able to spend the UTXO.
3. Creating withdrawal fulfillment transaction (note that in 0.1, withdrawal requests are smart contract calls)
4. Creating a sBTC wallet handoff  transaction.
5. Reading and parsing a deposit reveal transaction on the bitcoin chain
6. Reading and parsing a withdrawal fulfillment transaction on the bitcoin chain

### Definition of done
The sBTC SDK supports the above functionality

**Comment by stjepangolemac** [comment]
I might be wrong but didn't we have the commit reveal logic written somewhere? In a PR or something like that?

**Comment by netrome** [comment]
Yep, in an old branch in the TrustMachines repo. I think we can port some of that. Here's the branch name: `281-library-for-constructing-and-verifying-commitreveal-bitcoin-transactions`.

**Comment by netrome** [comment]
Legacy issue for context: https://github.com/Trust-Machines/stacks-sbtc/issues/281

**Comment by stjepangolemac** [comment]
Awesome, thank you 🫡
