### ISSUE TITLE
[Feature]: Emily Event Observer Sidecar

### ISSUE THREAD

**Issue by AshtonStephens** [stacks-network/sbtc#340]
# Feature - Emily Event Observer Sidecar

## 1. Description

This ticket is to implement the Emily event observer which will update the API with events that are considered trusted. 

How to handle the events is linked below:

### 1.1 Context & Purpose
The API sidecar will ingest the information required to update operation status based on the event data printed to chain and sent to the event observer. The sBTC operation clarity contracts will need to publish specific information about a transaction’s status when processing an sBTC operation.

This Sidecar will be updating the API database to be consistent.

## 2. Technical Details:

Technical details are in the link above, reposting here:
- #50 -> [Google Doc](https://docs.google.com/document/d/13AN9GdLfPYKKPkeHNU4niq_CyJCDxFR7DGBLzLc5gxU/edit#heading=h.jkxgl5anwobj)

### 2.1 Acceptance Criteria:
   - [ ] The sidecar can take in clarity events as described in the LLD
   - [ ] The sidecar is tested to the best of current ability in integration tests.
   - [ ] PR is created and merged 

## 3. Related Issues and Pull Requests (optional):
- Low level design: #50
    - [Event observer sidecar specific design](https://docs.google.com/document/d/13AN9GdLfPYKKPkeHNU4niq_CyJCDxFR7DGBLzLc5gxU/edit#heading=h.jkxgl5anwobj)

**Comment by djordon** [comment]
Hmm, might be simpler than we think to do this. I was just looking and it looks like we might be able to specify that we only want [smart-contract-events](https://github.com/stacks-network/stacks-core/blob/47db1d0a8bf70eda1c93cb3e0731bdf5595f7baa/testnet/stacks-node/src/config.rs#L2822-L2823). I think these [lines dictate the format](https://github.com/stacks-network/stacks-core/blob/47db1d0a8bf70eda1c93cb3e0731bdf5595f7baa/testnet/stacks-node/src/config.rs#L2866-L2897).

**Comment by AshtonStephens** [comment]
This totally makes sense, @jovanvuleta are you familiar with how to execute the smart contracts on a local environment?

**Comment by jovanvuleta** [comment]
Until now I have been deploying our contracts via clarinet integrate, will I be able to do the same here or is the flow different? @AshtonStephens

**Comment by AshtonStephens** [comment]
Look here for some existing sidecar code: signer/src/stacks/webhooks.rs

**Comment by AshtonStephens** [comment]
This may be best doable in the sBTC Signer, design issue linked #687
