### ISSUE TITLE
[Chore]: Investigate Status of K8s and Docker Compose PRs

### ISSUE THREAD

**Issue by AshtonStephens** [stacks-network/sbtc#355]
# Chore - Investigate Status of K8s and Docker Compose PRs

This ticket holds the research relating to Investigate Status of K8s and Docker Compose PRs and how it impacts sBTC.

## 1. Summary

We have some old pull requests created and closed to add a persistent environment to sBTC. This ticket is to look at them and determine what we can use.

- https://github.com/stacks-network/sbtc/pull/240
- https://github.com/stacks-network/sbtc/pull/241

**Comment by jovanvuleta** [comment]
I was able to run properly the local k8s setup on the branch: https://github.com/stacks-network/sbtc/pull/241
I think it can be merged but I would like to advise with Hank about that beforehand.

The current issue that is still present in both our docker compose and local k8s devnet is that the chain will halt/stop after some random time.

The issue itself comes from base image of stacks-core and doesn't have to do anything with our local devnet setup.

Stacks container error logs:
`ERRO [1721905748.342970] [testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs:745] [miner-block-http://0.0.0.0:20443] Bitcoin RPC failure: error listing utxos Network(“Bitcoin RPC: status(500) != success, body is ‘Object {\“error\“: Object {\“code\“: Number(-8), \“message\“: String(\“Block height out of range\“)}, \“id\“: String(\“stacks\“), \“result\“: Null}’“)
INFO [1721905748.841064] [stackslib/src/net/rpc.rs:556] [p2p-(0.0.0.0:20444,0.0.0.0:20443)] Handled StacksHTTPRequest, verb: GET, path: /v2/info, processing_time_ms: 0, latency_ms: 0, conn_id: 357, peer_addr: 10.1.2.35:51544
WARN [1721905748.939956] [stackslib/src/burnchains/bitcoin/spv.rs:1024] [main] Received discontiguous headers at height 709: we have child LoneBlockHeader { header: BlockHeader { version: 536870912, prev_blockhash: 11615f456c380f9993732c494dcb22b485cc9c80b5af32871239186052e2ea36, merkle_root: bb7b3f80af39940a4379fb418a6e9bdf33d63621105187cc7ea4c3d18f943843, time: 1721835037, bits: 545259519, nonce: 0 }, tx_count: VarInt(0) } (38acb6e368902b1ec4801046c5a291f05c70514ab8766b968152c386f9dd7034), but were given LoneBlockHeader { header: BlockHeader { version: 536870912, prev_blockhash: 11615f456c380f9993732c494dcb22b485cc9c80b5af32871239186052e2ea36, merkle_root: bb7b3f80af39940a4379fb418a6e9bdf33d63621105187cc7ea4c3d18f943843, time: 1721835037, bits: 545259519, nonce: 0 }, tx_count: VarInt(0) } (38acb6e368902b1ec4801046c5a291f05c70514ab8766b968152c386f9dd7034)
ERRO [1721905748.941752] [stackslib/src/burnchains/burnchain.rs:1070] [main] Failed to check for reorgs from /var/stacks/krypton/headers.sqlite: Bitcoin(NoncontiguousHeader)
ERRO [1721905748.941828] [testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs:549] [main] Unable to sync with burnchain: Non-contiguous header`
