### ISSUE TITLE
[Research]: Signer control plane API

### ISSUE THREAD

**Issue by djordon** [stacks-network/sbtc#40]
***Completing the issue description and arriving at a conclusion is the deliverable of this issue.***

# Research - Signer control plane API

This ticket holds the research relating to which endpoints signers must expose as part of their API and how it impacts sBTC withdrawals and deposits.

## 1. Summary

User and operators of our sBTC process would like to have visibility into the actions of the signers. This ticket fleshes out which actions are needed and the APIs that are necessary to support them.

### 3.3 Areas of Ambiguity

---

**Closing Checklist**
- [ ] The takeaway from this issue is clearly documented in the description of this ticket.
- [ ] Everyone necessary has reviewed the resolution and agrees with the takeaways.
- [ ] This ticket has or links all the information necessary to familiarize a contributor with the topic and how it was resolved.

**Comment by AshtonStephens** [comment]
Not planned, see #44. We don't plan on revisiting.
