### ISSUE TITLE
[Feature]: Add handler for smart contract events from a stacks node

### ISSUE THREAD

**Issue by djordon** [stacks-network/sbtc#426]
# Feature - Add handler for new smart contract events from a stacks node

## 1. Description

The signers should add an endpoint that their stacks node sends webhooks to for smart contract events. Write sBTC-relevant transactions with their associated events to the database.

### 1.1 Context & Purpose

Each `accept-withdrawal-request` contract call uses a `request-id` as input into the function call. This `request-id` is returned as the contract call output, and is emitted as a print event during the contract call. These events (print events and probably the return events) seem to be the only way to get the `request-id` associated with the contract call. Since these events are emitted as webhooks by the stacks node, we need to add a handler to listen for them.

Note 1: this `request-id` is used to store the input variables used in the `initiate-withdrawal-request` contract call made by the user. It also serves as a way to ensure that both `withdrawal-accept` and `withdrawal-reject` contract calls cannot succeed for the same initial `initiate-withdrawal-request` contract call.

Note 2: I think these events are the only way to know if a transaction failed, since the transaction is still stored on the blockchain, but it's success or failure is not.

### 2.1 Acceptance Criteria:
   - [ ] We have an endpoint that listens to smart contract events from the stack node.
   - [ ] We write the relevant transactions and their events to the database.

**Comment by cylewitruk** [comment]
> Note 2: I think these events are the only way to know if a transaction failed, since the transaction is still stored on the blockchain, but it's success or failure is not.

This is correct
