### ISSUE TITLE
[Feature]: Add a command to signer binary to generate a new Stacks keychain

### ISSUE THREAD

**Issue by cylewitruk** [stacks-network/sbtc#433]
# Feature - Add a command to signer binary to generate a new Stacks keychain

## 1. Description

Provide a signer-native way of generating new Stacks keychains to avoid the need for additional external tooling.

### 1.1 Context & Purpose
Stacks private keys as generated today by existing tooling include an extra byte marker in their serialized private key making the key 33 bytes instead of 32. This byte marker is used by `stacks-core` when initializing its `StacksPrivateKey` instance and indicates to the instance whether or not its corresponding public key is compressed (33 bytes) or uncompressed (65 bytes) (details [here](https://learnmeabitcoin.com/technical/keys/public-key/)).

While realistically uncompressed public keys are deprecated and stacks-core now always sets a "true" byte marker, this byte is still appended on Stacks tooling-generated private keys (including the [Stacks CLI](https://www.npmjs.com/package/@stacks/cli)), which is irrelevant for the signer and deviates from standard secp256k1.

Speaking with @djordon, it sounds like signers should probably avoid using preexisting keys and that we'd like to keep this kind of deviation from secp256k1 away from the signer and only support standardized secp256k1 constructs. Thus, providing the means to generate a new, "clean" private key natively in the signer binary would remove the need for a) extra tooling, and (b) the need to manually modify a Stacks-generated private key by removing the last two characters of its hex-encoded representation.

## 2. Technical Details:
Such a command should produce at least the following information to the user:
- Mnemonic: for importing the keychain into Stacks wallets such as Leather
- Private key: the hex-encoded 32-byte private key
- Public key: the hex-encoded 33-byte (compressed) public key. _This isn't necessarily required but can be a nice-to-have -- do we want this?_

The [Stacks CLI](https://www.npmjs.com/package/@stacks/cli)'s `make_keychain` command also outputs `address`, `wif`, `index` and `btcAddress`, but I'm not sure that these are relevant for the signer. Both the STX and BTC addresses can be derived later from the private key using the Stacks CLI's `get_address` function.

### 2.1 Acceptance Criteria:
   - [ ] A new CLI command in the signer generates a new secp256k1 private key and outputs the private key, public key(?) and mnemonic.
   - [ ] The Stacks CLI can be used to retrieve the corresponding STX and BTC addresses

## 3. Related Issues and Pull Requests (optional):
Discussed in the comments in #428

**Comment by cylewitruk** [comment]
@djordon vote that we close this for now as we've re-enabled 33-byte stacks private keys and chances are the keys will be generated using Stacks-described methods for stacking.

Thoughts?

**Comment by djordon** [comment]
Yeah we can close this. I also forgot that they won't be generating a new key for the sBTC signer anyway.
