### ISSUE TITLE
[Feature]: Store contract call transaction failures

### ISSUE THREAD

**Issue by djordon** [stacks-network/sbtc#475]
# Feature - Store contract call transaction failures

## 1. Description

We store the raw transaction for all sBTC related transactions, but we do not store whether the transaction execution resulted in a success or a failure. For most sBTC related transactions, their success can be inferred by the associated events that are emitted, but we do not explicitly store the failure response when they fail.

Note that, we do not get emit events for rotate-keys contract calls but we can infer their success or failure by looking at the data variable in the smart contract. But it would be best to be explicit here too.

### 1.1 Context & Purpose

The expectation now is that the sbtc-signer's stacks node has a stanza in it's config that looks like:
```toml
[[events_observer]]
endpoint = "<url-to-sbtc-signer>:8801"
retry_count = 3
include_data_events = false
events_keys = [
    "<signers-joint-address>.sbtc-registry::print",
]
```
I'm not sure what else needs to be added in order for all sbtc transactions receipts are emitted as well. Also, I don't know what `include_data_events` does.

But the goal is to figure out what needs to change (if anything) so that all sBTC related transactions are included in `POST /new_block` webhooks. Moreover, we need to make the necessary changes to the `stacks_transactions` table so that we store their success and failure.

### 2.1 Acceptance Criteria:
   - [ ] Store the transaction execution success and failure response in the signer's database.
   - [ ] We update out docs so that we know how a stacks node is supposed to be configured to emit events.

## 3. Related Issues and Pull Requests (optional):

This would loop into the event handler after https://github.com/stacks-network/sbtc/issues/426 is completed.

**Comment by cylewitruk** [comment]
So looking at the Stacks core code, it seems that both `retry_count` and `include_data_events` have no effect, they're not read from the config file (or env vars).

**Comment by djordon** [comment]
... Okay, not super surprising. That's what I originally [thought](https://github.com/stacks-network/sbtc/pull/442/commits/5f964b4b90e58338a2cbf5564ebce499d92c04f0#diff-02371c50dd29e828f7dccc12538e6c63d866a524fa644afb0c6e09d91384adf1R14-R27) when I was looking through the code. When I "discovered" that config option I foolishly assumed that it did the reasonable thing.

**Comment by aldur** [comment]
Closing a we decided this is not required.
