### ISSUE TITLE
[Feature]: Add support for multiple bitcoin nodes for `BitcoinCoreClient`

### ISSUE THREAD

**Issue by cylewitruk** [stacks-network/sbtc#486]
# Feature - Add support for multiple bitcoin nodes for `BitcoinCoreClient`

## 1. Description

On par with #484 which allows the configuration of multiple Bitcoin RPC endpoints, we need a mechanism for being able to use multiple endpoints like was done with `StacksClient` in #225.

### 1.1 Context & Purpose
Just like with Stacks nodes, we should support multiple Bitcoin nodes. The primary driver for this is so that the Signer doesn't need to experience potential downtime if a Bitcoin Core node is being updated if the operator runs two Bitcoin nodes.

## 2. Technical Details:
We can either implement this as a part of the `BitcoinCoreClient` like was done with `StacksClient`, or we could implement a pooling wrapper over the client.

### 2.1 Acceptance Criteria:
   - [ ] If multiple Bitcoin RPC endpoints are specified and a connection to one fails, the remaining endpoints should be tried, until the available endpoints have been exhausted, then an error should be returned.

## 3. Related Issues and Pull Requests (optional):
- #484

**Comment by djordon** [comment]
I think this was closed in https://github.com/stacks-network/sbtc/pull/549.
