### ISSUE TITLE
[Feature]: Fee is not refunded to the user in the event of a rejection

### ISSUE THREAD

**Issue by evonide** [stacks-network/sbtc#503]
# (Low) Fee is not refunded to the user in the event of a rejection

## 1. Description

During a withdrawal rejection by the signer, the locked amount is refunded to the user but the [fee component is not](https://github.com/stacks-network/sbtc/blob/3da6e48a7bc471e1edd1bd21aa24cb10d760555e/contracts/contracts/sbtc-withdrawal.clar#L100-L101). Because the fee is not even locked up yet, this does not pose the issue but once the implementation is fixed this will pose a problem as rejected users will lose funds.

**Comment by djordon** [comment]
Oh, great call out. The current PR for these changes (https://github.com/stacks-network/sbtc/pull/498) does not refund the user during a rejection. Will change.
