### ISSUE TITLE
[Feature]: Inconsistent code comment

### ISSUE THREAD

**Issue by evonide** [stacks-network/sbtc#504]
# (Low, non-security) Inconsistent code comment

## 1. Description

The comment [here](https://github.com/stacks-network/sbtc/blob/3da6e48a7bc471e1edd1bd21aa24cb10d760555e/contracts/contracts/sbtc-deposit.clar#L61-L63) is wrong since the list is 650 in length.

**Comment by friedger** [comment]
Similar here: https://github.com/stacks-network/sbtc/blob/3da6e48a7bc471e1edd1bd21aa24cb10d760555e/contracts/contracts/sbtc-bootstrap-signers.clar#L103

Only 15 signers can be used to bootstrap, not 128.

**Comment by djordon** [comment]
> Similar here:
> 
> https://github.com/stacks-network/sbtc/blob/3da6e48a7bc471e1edd1bd21aa24cb10d760555e/contracts/contracts/sbtc-bootstrap-signers.clar#L103
> 
> Only 15 signers can be used to bootstrap, not 128.

Oh, do you mean that the file should be renamed?

**Comment by friedger** [comment]
> > Similar here:
> > https://github.com/stacks-network/sbtc/blob/3da6e48a7bc471e1edd1bd21aa24cb10d760555e/contracts/contracts/sbtc-bootstrap-signers.clar#L103
> > 
> > Only 15 signers can be used to bootstrap, not 128.
> 
> Oh, do you mean that the file should be renamed?

No, the list suggest 128, but the iterator only accepts 15 signers

**Comment by friedger** [comment]
Similar here:

https://github.com/stacks-network/sbtc/blob/main/contracts/contracts/sbtc-bootstrap-signers.clar#L45

The comment suggest that contract-caller is checked, however, the tx-sender is checked. Which one is the correct check?

**Comment by setzeus** [comment]
> > > Similar here:
> > > https://github.com/stacks-network/sbtc/blob/3da6e48a7bc471e1edd1bd21aa24cb10d760555e/contracts/contracts/sbtc-bootstrap-signers.clar#L103
> > > 
> > > Only 15 signers can be used to bootstrap, not 128.
> > 
> > 
> > Oh, do you mean that the file should be renamed?
> 
> No, the list suggest 128, but the iterator only accepts 15 signers

I think we agreed on 128 as a max? So as a way to future-proof we set the upper limit in the 'sbtc-registry' to 128. At least in the contracts there's no limit of 15 signers anywhere else?

**Comment by setzeus** [comment]
> Similar here:
> 
> https://github.com/stacks-network/sbtc/blob/main/contracts/contracts/sbtc-bootstrap-signers.clar#L45
> 
> The comment suggest that contract-caller is checked, however, the tx-sender is checked. Which one is the correct check?

Copy. Updated to specify 'tx-sender.'

**Comment by friedger** [comment]
> > > > Similar here:
> > > > https://github.com/stacks-network/sbtc/blob/3da6e48a7bc471e1edd1bd21aa24cb10d760555e/contracts/contracts/sbtc-bootstrap-signers.clar#L103
> > > > 
> > > > Only 15 signers can be used to bootstrap, not 128.
> > > 
> > > 
> > > Oh, do you mean that the file should be renamed?
> > 
> > 
> > No, the list suggest 128, but the iterator only accepts 15 signers
> 
> I think we agreed on 128 as a max? So as a way to future-proof we set the upper limit in the 'sbtc-registry' to 128. At least in the contracts there's no limit of 15 signers anywhere else?

There are in the iterator. The buffer length is 510 = 15 signers

**Comment by djordon** [comment]
Yeah gotcha, from https://github.com/stacks-network/sbtc/blob/3da6e48a7bc471e1edd1bd21aa24cb10d760555e/contracts/contracts/sbtc-bootstrap-signers.clar#L102-L110 So for v2 we _have_ to upgrade this contract unless we fix this now.

**Comment by djordon** [comment]
Oh right, I updated this a while ago and didn't update the buff value. I even updated the comment and forgot to change the buff value 🤦🏽‍♂️. Okay, I'll fix this all now.
