### ISSUE TITLE
[Bug]: `Url` crate parses ip4 addresses as DNS names

### ISSUE THREAD

**Issue by cylewitruk** [stacks-network/sbtc#513]
# Bug -`Url` crate parses ip4 addresses as DNS names

## 1. Description

This is a problem in the signer config.

The URL crate seems to parse i.e. `tcp://0.0.0.0:4122` as a DNS host for some reason (when checking it via the `host()` method), which results in a multiaddr of `dns/0.0.0.0/tcp/4122` which is invalid according to libp2p and causes the swarm to fail to start up.

It looks like there are some nuances re: ipv6 as well when parsing the port.

### 2.1 Acceptance Criteria:
   - [ ] IPv4 addresses result in an `ip4` multiaddr
   - [ ] IPv6 addresses result in an `ip6` multiaddr
   - [ ] DNS hosts result in a `dns` multiaddr

**Comment by djordon** [comment]
Closes in https://github.com/stacks-network/sbtc/pull/521.
