### ISSUE TITLE
[Feature]: BTC deposit tx validation returns potentially unvalidated script data

### ISSUE THREAD

**Issue by evonide** [stacks-network/sbtc#514]
# (Low) Bitcoin deposit tx validation stores potentially unvalidated script data

## 1. Description

This concerns [sbtc/sbtc/src/deposits.rs at 9c7b66525c02eeba64f3d6b0aaa4f9bd1a20a62e · stacks-network/sbtc](https://github.com/stacks-network/sbtc/blob/9c7b66525c02eeba64f3d6b0aaa4f9bd1a20a62e/sbtc/src/deposits.rs#L158):
```
    /// Validate this deposit request.
[...]
    /// * That the deposit script and reclaim script in the request match
    ///   the expected formats for deposit transactions.
    /// * That deposit script and the reclaim script are part of the UTXO
    ///   ScriptPubKey.
    pub fn validate_tx(&self, tx: &Transaction) -> Result<DepositInfo, Error> {
[...]
        // Validate that the deposit and reclaim scripts in the request
        // match the expected formats for deposit transactions.
        let deposit = DepositScriptInputs::parse(&self.deposit_script)?;
        let reclaim = ReclaimScriptInputs::parse(&self.reclaim_script)?;
        // Okay, the deposit and reclaim scripts are valid. Now make sure
        // that the ScriptPubKey in the transaction matches the one implied
        // by the given scripts. So now create the expected ScriptPubKey.
        let deposit_script = deposit.deposit_script();
        let reclaim_script = reclaim.reclaim_script();

        debug_assert_eq!(deposit_script, self.deposit_script); // <-- Skipped in production
        debug_assert_eq!(reclaim_script, self.reclaim_script);  // <-- Skipped in production

        let expected_script_pubkey = to_script_pubkey(deposit_script, reclaim_script);
        // Check that the expected scriptPubkey matches the actual public
        // key of our parsed UTXO.
        if expected_script_pubkey != tx_out.script_pubkey {
            return Err(Error::UtxoScriptPubKeyMismatch(self.outpoint));
        }

        Ok(DepositInfo {
            max_fee: deposit.max_fee,
            deposit_script: self.deposit_script.clone(), // <-- Using the initial data instead of `deposit_script`
            reclaim_script: self.reclaim_script.clone(), // <-- Using the initial data instead of `reclaim_script`
            signers_public_key: deposit.signers_public_key,
            recipient: deposit.recipient,
            lock_time: reclaim.lock_time as u64,
            amount: tx_out.value.to_sat(),
            outpoint: self.outpoint,
        })
    }
```

1. The block observer fetches a bitcoin transaction from the chain given the `txid` which was registered over the Emily API by a user.
2. There are two scripts [deposit and reclaim] which can be used by either the signers to spend the pending BTC or the user to reclaim them if specific conditions are met. It ensures the attached scripts have a valid format and can be parsed.
3. Note that the code uses `debug_assert_eq!` for comparison on the parsed scripts. However, these checks won't run in production.
4. In addition, the code ensures that the generated `script_pubkey` from the parsed deposit and reclaim scripts matches the provided one in `tx_out.script_pubkey`.
5. Finally, `validate_tx` returns a `DepositInfo` with the scripts from the original Emily API input. 

Note that validating a processed form of data but then using the original data is an anti-pattern. For example, it's not necessarily guaranteed that:
```
assert_eq!(
  DepositScriptInputs::parse(&self.deposit_script)?.deposit_script(),
  self.deposit_script
);
```
will always be true for all possible `self.deposit_script` and you might get inconsistencies. In this instance, both the deposit and reclaim parsing seem to consume every single bit of the data so that's likely less of a problem.

Recommendation: This can be easily mitigated by returning the parsed and restored `deposit_script` and `reclaim_script` in `DepositInfo` instead of using `self.deposit_script` and `self.reclaim_script` respectively.

**Comment by djordon** [comment]
Good call out. Easy fix.

**Comment by djordon** [comment]
> For example, it's not necessarily guaranteed that:
> 
> ```
> assert_eq!(
>   DepositScriptInputs::parse(&self.deposit_script)?.deposit_script(),
>   self.deposit_script
> );
> ```
> will always be true for all possible `self.deposit_script` and you might get inconsistencies.

I think it's worth adding a little more detail for why this is the case as it's not clear to me how this can come to be.

**Comment by djordon** [comment]
This has been fixed, but I'm still curious about how the re-generated deposit script and the given deposit script could diverge.

**Comment by evonide** [comment]
Thanks Daniel,

There are two questions here:
1. Can we guarantee that the reconstruction of a parsed (reclaim/deposit) script will always be exactly correct for every single bit?
2. What is the impact of storing a slightly deviating or inconsistent script?

For 2. there currently might be none as we store the script data purely for informational purposes.

Answering 1. might be more tricky. This would be a perfect candidate for fuzzing. One simple example that comes to mind is integer parsing. You might truncate parts of the most significant bits in the binary representation. For example, say you have a u32 but your binary format supports u64. The upper 32 bits could be ignored and hence a reconstruction could contain inconsistent data.

I don't have any specific example where I'm sure this is possible with the current code. However, to illustrate the problem consider this:

https://github.com/stacks-network/sbtc/blob/ffbe79e0238825f3546e9429bbf89042703823df/sbtc/src/deposits.rs#L342-L350

Note that this code supports both `OP_PUSHDATA1` and `OP_PUSHBYTES_75` and there's this code:
```
[OP_PUSHDATA1, n, data @ ..] if data.len() == *n as usize && *n < 160 => data,
```
I think this should technically be `if data.len() == *n as usize && *n > 75 && *n < 160 => data,` as otherwise you could in theory construct scripts where `[OP_PUSHDATA1 50]` would be accepted as well as `[50 ...]`.

So if you have as an input:

```
[OP_PUSHDATA1, 50, ...]
```

when parsed and reconstructed you might then get:

```
[OP_PUSHBYTES_50, ...]
```

As it's colloquial to use OP_PUSHBYTES_N for anything <= 75.

In general, the takeaway here is that it'll be hard to always guarantee bit identical reconstructions. The implications of which are very context dependent as mentioned. Hope this helps?

**Comment by djordon** [comment]
Yes, this helps a lot. Thanks for taking the time to give an answer too, it was very much appreciated.
