### ISSUE TITLE
[Feature]: Add db endpoint configuration

### ISSUE THREAD

**Issue by cylewitruk** [stacks-network/sbtc#520]
# Feature - Add db endpoint configuration

## 1. Description

The database endpoint is currently hardcoded in the signer. Make this configurable in the config.

### 1.1 Context & Purpose
It will be required that a signer can configure their own database endpoint depending on their environment.

## 2. Technical Details:
Add `db_endpoint` to the `signer` config section. This should support `postgresql` URI's.

### 2.1 Acceptance Criteria:
   - [ ] Database endpoint can be configured via both config file and environment variable.
   - [ ] Database connections are opened using the configured endpoint and not hardcoded.

**Comment by djordon** [comment]
Closes in https://github.com/stacks-network/sbtc/pull/521.
