### ISSUE TITLE
[Feature]: Block observer is skipping certain deposit requests

### ISSUE THREAD

**Issue by technovision99** [stacks-network/sbtc#522]
# (High) Block observer is skipping certain deposit requests

## 1. Description
The block observer iterates over new bitcoin blocks:
https://github.com/stacks-network/sbtc/blob/033e2cbd2def829a3e30df77bc274b325d68cdbe/signer/src/block_observer.rs#L78-L97

It then calls into `process_bitcoin_block` which in turn calls `extract_deposit_requests`:
https://github.com/stacks-network/sbtc/blob/033e2cbd2def829a3e30df77bc274b325d68cdbe/signer/src/block_observer.rs#L157-L185

Note that this means any deposits fetched from the API that reference an old block will effectively be skipped. We should ensure that all deposits can still be processed even if they reference blocks before the new bitcoin blocks fetched from the bitcoin client. 

As discussed, please deduplicate if there's already a tracking bug for this.

**Comment by djordon** [comment]
Yeah this slipped through the cracks. Thanks for opening the issue.

**Comment by cylewitruk** [comment]
Pausing work on this in favor of #667 for demo

**Comment by djordon** [comment]
This isn't actually closed. We need to make sure we get the bitcoin block associated with each deposit transaction first.

**Comment by djordon** [comment]
Actually, this may indeed be fixed if we do https://github.com/stacks-network/sbtc/issues/685.

**Comment by djordon** [comment]
Quick update here, I don't think https://github.com/stacks-network/sbtc/issues/685 solves the outstanding issue. It might be worth doing for other reasons but this ticket probably isn't one of them. Some notes
1. The block observer no longer skips certain deposits. A request is only written to the database if it has been confirmed.
2. The signer does not check to see if the block confirming the deposit is in the database before attempting to write the deposit transaction to the database. That is the outstanding problem with the current code. We have a foreign key constraint on the `bitcoin_transactions` table that will be violated if we do not know about the block.
3. I don't think [#685](https://github.com/stacks-network/sbtc/issues/685) solves this. A transaction may be confirmed on a block that is not on the best chain, but I believe that bitcoin-core only sends ZeroMQ notifications when a block has been added to the best chain (from the [docs here](https://github.com/bitcoin/bitcoin/blob/2a52718d734cf65aaeeb18f627547e5bca3483f4/doc/zmq.md)). This means that it may be possible for a deposit request to pass validation but where the signer do not have the block in our database.

So the solution is, before writing the transaction, check to see if the signer knows about the block confirming the deposit transaction and add the block to the database if it does not.

**Comment by djordon** [comment]
I opened https://github.com/stacks-network/sbtc/issues/731 to fix the bug noted in https://github.com/stacks-network/sbtc/issues/522#issuecomment-2440545467. The issue raised here was fixed by https://github.com/stacks-network/sbtc/pull/679.
