### ISSUE TITLE
[Feature]: Get last fee for bitcoin transactions

### ISSUE THREAD

**Issue by djordon** [stacks-network/sbtc#541]
# Feature - Get Last Fee for bitcoin transactions

## 1. Description

Before we can replace-by-fee (RBF) a bitcoin transaction, we need to fetch the fee that was paid for the last transaction *package* that is currently in the mempool.

### 1.1 Context & Purpose

In order to RBF a transaction you need to know how much you paid both in total and per vbyte in order to know whether the new fee would be accepted. Since we could be replacing an entire package, we need to know the fees paid for all signer transactions in the mempool. Each of these transactions has their first input and output with a `scriptPubKey` that is in the `dkg_shares` table.

## 2. Technical Details:

Might be easiest to use the [`gettxspendingprevout`](https://bitcoincore.org/en/doc/27.0.0/rpc/blockchain/gettxspendingprevout/) and [`getmempooldescendants`](https://bitcoincore.org/en/doc/27.0.0/rpc/blockchain/getmempooldescendants/) RPC calls on bitcoin-core since we know the previous signer UTXO once https://github.com/stacks-network/sbtc/issues/538 is done.

### 2.1 Acceptance Criteria:

- [ ]  The `BitcoinInteract::get_last_fee` returns the fee paid for the current outstanding transaction package in the mempool.

## 3. Related Issues and Pull Requests (optional):

**Comment by djordon** [comment]
Yes.

**Comment by cylewitruk** [comment]
Replaced by #809
