### ISSUE TITLE
[sBTC DR] Document architecture and roadmap (sbtc-docs)

### ISSUE THREAD

**Issue by jferrant** [stacks-network/sbtc#58]
The sBTC Developer release needs to be documented as part of [sBTC docs](https://github.com/stacks-network/sbtc-docs). This should include the architecture diagrams and estimated timeline/deliverables/and product requirements. 

Definition of Done:
sBTC Developer Release is fully documented within sbtc-docs.

**Comment by netrome** [comment]
Closing in favor of docs issue: https://github.com/stacks-network/sbtc-docs/issues/74
