### ISSUE TITLE
[Design]: Signer tables

### ISSUE THREAD

**Issue by netrome** [stacks-network/sbtc#60]
***Completing the issue description and arriving at a conclusion is the deliverable of this issue.***

# Design - Signer tables

This ticket holds the design of the signer tables and how it fits into sBTC v1.

## 1. Summary
The sBTC bootstrap signer will hold a lot of state to maintain it's operations. This issue outlines the table layout we envision for the signers in postgres flavoured SQL.

## 2. Context & Purpose
The purpose of this design is to create the base table layout that we can base the subsequent LLD documents on top of.

***Relevant Research Discussions***
#44 

### 3.1 Proposed Component Design

```sql
CREATE TABLE bitcoin_blocks (
    block_hash BYTEA PRIMARY KEY,
    block_height BIGINT NOT NULL,
    parent_hash BYTEA NOT NULL,
    confirms BYTEA, /* Stacks blocks confirmed by this bitcoin block */
    created_at TIMESTAMP NOT NULL.
);

CREATE TABLE stacks_blocks (
    block_hash BYTEA PRIMARY KEY,
    block_height BIGINT NOT NULL,
    parent_hash BYTEA NOT NULL,
    created_at TIMESTAMP NOT NULL,
);

CREATE TABLE deposit_requests (
    txid BYTEA NOT NULL,
    output_index INTEGER NOT NULL,

    spend_script BYTEA NOT NULL,
    reclaim_script BYTEA NOT NULL,
    
    recipient TEXT NOT NULL,
    amount BIGINT NOT NULL,
    max_fee BIGINT NOT NULL,
    
    created_at TIMESTAMP NOT NULL,
    PRIMARY KEY (txid, output_index)
);

CREATE TABLE deposit_signers (
    txid BYTEA NOT NULL,
    output_index INTEGER NOT NULL,
    signer_pub_key BYTEA NOT NULL,
    is_accepted BOOL NOT NULL,
    created_at TIMESTAMP NOT NULL,
    PRIMARY KEY (txid, output_index, signer_pub_key),
    FOREIGN KEY (txid, output_index) REFERENCES deposit_requests(txid, output_index) ON DELETE CASCADE,
);

CREATE TABLE withdraw_requests (
    request_id INTEGER NOT NULL,
    block_hash BYTEA NOT NULL,
    
    recipient BYTEA NOT NULL,
    amount BIGINT NOT NULL,
    max_fee BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    PRIMARY KEY (request_id, block_hash),
    FOREIGN KEY (block_hash) REFERENCES stacks_blocks(block_hash) ON DELETE CASCADE,
);

CREATE TABLE withdraw_signers (
    request_id INTEGER NOT NULL,
    block_hash BYTEA NOT NULL,
    signer_pub_key BYTEA NOT NULL,
    is_accepted BOOL NOT NULL,
    created_at TIMESTAMP NOT NULL,
    PRIMARY KEY (request_id, block_hash, signer_pub_key),
    FOREIGN KEY (request_id, block_hash) REFERENCES withdraw_requests(request_id, block_hash) ON DELETE CASCADE,
);

CREATE TYPE transaction_type AS ENUM (
    'sbtc_transaction',
    'withdraw_accept',
    'withdraw_reject',
    'deposit_accept',
    'update_signer_set',
    'set_aggregate_key',
);

CREATE TABLE transactions (
    txid BYTEA PRIMARY KEY,
    tx BLOB NOT NULL,
    tx_type transaction_type NOT NULL,
    created_at TIMESTAMP NOT NULL,
);

CREATE TABLE dkg_shares (
    aggregate_key BYTEA PRIMARY KEY,
    tweaked_aggregate_key BYTEA NOT NULL,
    encrypted_shares BLOB NOT NULL,
    created_at TIMESTAMP NOT NULL,
);

CREATE TABLE coordinator_broadcasts (
    broadcast_id SERIAL PRIMARY KEY,
    txid BYTEA NOT NULL,
    broadcast_block_height INTEGER NOT NULL,
    market_fee_rate INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL,
    
    FOREIGN KEY (txid) REFERENCES transactions(txid) ON DELETE CASCADE,
);

-- Junction tables to model many-to-many relationships

CREATE TABLE bitcoin_transactions (
    txid BYTEA NOT NULL,
    block_hash BYTEA NOT NULL,
    PRIMARY KEY (txid, block_hash),
    FOREIGN KEY (txid) REFERENCES transactions(txid) ON DELETE CASCADE,
    FOREIGN KEY (block_hash) REFERENCES bitcoin_blocks(block_hash) ON DELETE CASCADE
);

CREATE TABLE stacks_transactions (
    txid BYTEA NOT NULL,
    block_hash BYTEA NOT NULL,
    PRIMARY KEY (txid, block_hash),
    FOREIGN KEY (txid) REFERENCES transactions(txid) ON DELETE CASCADE,
    FOREIGN KEY (block_hash) REFERENCES stacks_blocks(block_hash) ON DELETE CASCADE
);

CREATE TABLE aggregate_key_transactions (
    txid BYTEA NOT NULL,
    aggregate_key BYTEA NOT NULL,
    PRIMARY KEY (txid, aggregate_key),
    FOREIGN KEY (txid) REFERENCES transactions(txid) ON DELETE CASCADE,
    FOREIGN KEY (aggregate_key) REFERENCES dkg_shares(aggregate_key) ON DELETE CASCADE
);

CREATE TABLE deposit_responses (
    response_txid BYTEA NOT NULL,
    deposit_txid BYTEA NOT NULL,
    deposit_output_index INTEGER NOT NULL,
);

CREATE TABLE withdraw_responses (
    response_txid BYTEA NOT NULL,
    withdraw_txid BYTEA NOT NULL,
    withdraw_request_id INTEGER NOT NULL,
);

```

### 3.1.1 Design Diagram

```mermaid
erDiagram
    bitcoin_blocks ||--o{ bitcoin_transactions : "has"

    stacks_blocks ||--o{ stacks_transactions : "has"

    deposit_requests ||--o{ deposit_signers : "approved by"
    deposit_requests ||--o{ bitcoin_transactions : "linked"
    deposit_requests ||--o{ deposit_responses : "linked"

    withdraw_requests ||--o{ withdraw_signers : "approved by"
    withdraw_requests ||--o{ stacks_transactions : "linked"
    withdraw_requests ||--o{ withdraw_responses: "linked"

    transactions ||--o{ bitcoin_transactions : "linked"
    transactions ||--o{ stacks_transactions : "linked"
    transactions ||--o{ aggregate_key_transactions : "has"

    dkg_shares ||--o{ aggregate_key_transactions : "linked"
    coordinator_broadcasts ||--o{ transactions: "linked"
```

### 3.1.2 Considerations & Alternatives
While we've chosen a relational model to represent this state, it's not obvious that it is the best fit. Because all the data is based on blockchain state which is naturally organized as a tree, a graph database like neo4j could be an interesting option. Other alternatives include document databases, simple KV stores or building a rich in-memory data structure updated through events in such a way that it is sufficient to store an event log to recover a state after a reboot.

### 3.2 Areas of Ambiguity
While the table layouts are defined here, we might need to extend the storage model to cover needs that pup up in the different LLDs.
---

**Closing Checklist**
- [ ] The design proposed in this issue is clearly documented in the description of this ticket.
- [ ] Everyone necessary has reviewed the resolution and agrees with the proposal.
- [ ] This ticket has or links all the information necessary to familiarize a contributor with the design decision, why it was made, and how it'll be included.

**Comment by djordon** [comment]
I could think of a few more things that would be useful for us to track.
1. The signer's UTXO. Although I'm thinking of a simple convention for knowing the signers' UTXO, it would be nice to have a good view of this in the database. I'm just not sure how it would all work though. For example, the signer could populate this data into the database easily, but what about the other signers? Would the coordinator have to tell them all? Seems tedious, so maybe this is a bad idea.
2. The market fee rate at the time of the BTC transaction. Just to make sure that the actual fee matches what we expect it to be.
3. The amounts for the withdrawal UTXOs. Actually, I suppose this is unnecessary since we can deserialize the transaction blob and get the information that way.
4. The block-height when a BTC transaction was submitted. I think we can infer this from the transactions table using the `created_at` columns so maybe this is unnecessary? Although I always prefer an explicit column it's simple to have, I'm not convinced this is needed.

One question that I have is how non-coordinator clients will know certain pieces of information, such as when a BTC transaction was submitted and what the TX ID was when we submitted it. Will the coordinator share this information after the fact?

**Comment by netrome** [comment]
>     1. The signer's UTXO. Although I'm thinking of a simple convention for knowing the signers' UTXO, it would be nice to have a good view of this in the database. I'm just not sure how it would all work though. For example, the signer could populate this data into the database easily, but what about the other signers? Would the coordinator have to tell them all? Seems tedious, so maybe this is a bad idea.

I think this is already implicitly tracked, since we track the sBTC transactions. So say the coordinator want to query the UTXO, it could look up the latest sBTC transaction and get the first output of this one. It should of course verify this with the Bitcoin blockchain to see the status of the transaction, but looking up the UTXO shouldn't be too hard.

>     2. The market fee rate at the time of the BTC transaction. Just to make sure that the actual fee matches what we expect it to be.

This should definitely be logged for posterity, but I'm hesitant to whether this is information we'd actually like to persist in the database.

>     3. The amounts for the withdrawal UTXOs. Actually, I suppose this is unnecessary since we can deserialize the transaction blob and get the information that way.

Yeah unless we'd want to do more advanced queries based on it, at which point it would make sense to store it explicitly. But if we just want to look up this information it shouldn't be too hard already.

>     4. The block-height when a BTC transaction was submitted. I think we can infer this from the transactions table using the created_at columns so maybe this is unnecessary? Although I always prefer an explicit column it's simple to have, I'm not convinced this is needed.

Hmm, this and the marked fee rate is information relating to the state of things when the coordinator submits things. Again, I think this is something for logs rather than the database but we could create a table for the coordinator submission history that connects transactions with some information from the coordinator when it submitted the transaction. This could be nice to have, but I'd call [YAGNI](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it) unless we know a specific scenario where we'd use this information.

**Comment by djordon** [comment]
>> 1. The signer's UTXO. Although I'm thinking of a simple convention for knowing the signers' UTXO, it would be nice to have a good view of this in the database. I'm just not sure how it would all work though. For example, the signer could populate this data into the database easily, but what about the other signers? Would the coordinator have to tell them all? Seems tedious, so maybe this is a bad idea.
>
> I think this is already implicitly tracked, since we track the sBTC transactions. So say the coordinator want to query the UTXO, it could look up the latest sBTC transaction and get the first output of this one. It should of course verify this with the Bitcoin blockchain to see the status of the transaction, but looking up the UTXO shouldn't be too hard.

Yeah, I agree that it's tracked by convention (by, say, being the first or last input and output). I would prefer this being explicit. When constructing a RBF transaction we can see which requests are outstanding, which have been confirmed, so we know which requests to include in the new BTC transactions. But it's not clear how we know the UTXO that is associated with the peg-wallet without the convention. I cannot find a simple way in either ElectrumX or bitcoin-core (but it's very possible that I just overlooked it). I would prefer to avoid adding an implicit convention like this.

> This should definitely be logged for posterity, but I'm hesitant to whether this is information we'd actually like to persist in the database.

Yeah I don't know. I tend to put lots of information in the database since I almost never regret doing so. If we think we might want it, I'd prefer it in the DB as well as in logs since logs are more ephemeral.

>> 4. The block-height when a BTC transaction was submitted. I think we can infer this from the transactions table using the created_at columns so maybe this is unnecessary? Although I always prefer an explicit column it's simple to have, I'm not convinced this is needed.
>
> Hmm, this and the marked fee rate is information relating to the state of things when the coordinator submits things. Again, I think this is something for logs rather than the database but we could create a table for the coordinator submission history that connects transactions with some information from the coordinator when it submitted the transaction. This could be nice to have, but I'd call [YAGNI](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it) unless we know a specific scenario where we'd use this information.

Yeah I was asking myself about how we would know that we need to RBF a transaction. We may need to be aggressive and just RBFing at every new block (at least for deposits), even if fees haven't markedly changed. And we can just use time to estimate the block height of a submitted transaction (so we know how many blocks have passed without it being confirmed).

> One question that I have is how non-coordinator clients will know certain pieces of information, such as when a BTC transaction was submitted and what the TX ID was when we submitted it. Will the coordinator share this information after the fact?

I'm still curious about this bit though. Maybe it's in one of the other LLDs, it's very possible that I missed it.

**Comment by netrome** [comment]
> Yeah, I agree that it's tracked by convention (by, say, being the first or last input and output). I would prefer this being explicit. When constructing a RBF transaction we can see which requests are outstanding, which have been confirmed, so we know which requests to include in the new BTC transactions. But it's not clear how we know the UTXO that is associated with the peg-wallet without the convention. I cannot find a simple way in either ElectrumX or bitcoin-core (but it's very possible that I just overlooked it). I would prefer to avoid adding an implicit convention like this.

It's a bit more explicit than just convention. The sBTC UTXO is paid to the signer address (derived from the aggregate public key), so you should be able to query it from ElectrumX or bitcoin-core, using for example the [listunspent](https://developer.bitcoin.org/reference/rpc/listunspent.html) RPC method.

**Comment by netrome** [comment]
> Yeah I don't know. I tend to put lots of information in the database since I almost never regret doing so. If we think we might want it, I'd prefer it in the DB as well as in logs since logs are more ephemeral.

Fair point. Let's add a table to track the transactions created by the coordinator.

**Comment by netrome** [comment]
>> One question that I have is how non-coordinator clients will know certain pieces of information, such as when a BTC transaction was submitted and what the TX ID was when we submitted it. Will the coordinator share this information after the fact?

> I'm still curious about this bit though. Maybe it's in one of the other LLDs, it's very possible that I missed it.

Right sorry I missed this question. I do believe you could query this information from the node, but I also imagine the coordinator sending updates to the Deposit API (or Emily) as noted in this [LLD](https://docs.google.com/document/d/13AN9GdLfPYKKPkeHNU4niq_CyJCDxFR7DGBLzLc5gxU/).

**Comment by djordon** [comment]
> > Yeah, I agree that it's tracked by convention (by, say, being the first or last input and output). I would prefer this being explicit. When constructing a RBF transaction we can see which requests are outstanding, which have been confirmed, so we know which requests to include in the new BTC transactions. But it's not clear how we know the UTXO that is associated with the peg-wallet without the convention. I cannot find a simple way in either ElectrumX or bitcoin-core (but it's very possible that I just overlooked it). I would prefer to avoid adding an implicit convention like this.
> 
> It's a bit more explicit than just convention. The sBTC UTXO is paid to the signer address (derived from the aggregate public key), so you should be able to query it from ElectrumX or bitcoin-core, using for example the [listunspent](https://developer.bitcoin.org/reference/rpc/listunspent.html) RPC method.

Oh perfect, thank you. No worries then.

**Comment by netrome** [comment]
@djordon what do you think about adding something like the following to track the transactions broadcasted by a particular coordinator?

```
CREATE TABLE coordinator_broadcasts (
    broadcast_id SERIAL PRIMARY KEY,
    txid BYTEA NOT NULL,
    broadcast_block_height INTEGER NOT NULL,
    market_fee_rate INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL,
    
    FOREIGN KEY (txid) REFERENCES transactions(txid) ON DELETE CASCADE,
);
```

**Comment by djordon** [comment]
> @djordon what do you think about adding something like the following to track the transactions broadcasted by a particular coordinator?
> 
> ```
> CREATE TABLE coordinator_broadcasts (
>     broadcast_id SERIAL PRIMARY KEY,
>     txid BYTEA NOT NULL,
>     broadcast_block_height INTEGER NOT NULL,
>     market_fee_rate INTEGER NOT NULL,
>     created_at TIMESTAMP NOT NULL,
>     
>     FOREIGN KEY (txid) REFERENCES transactions(txid) ON DELETE CASCADE,
> );
> ```

Looks good to me!

**Comment by djordon** [comment]
> > > One question that I have is how non-coordinator clients will know certain pieces of information, such as when a BTC transaction was submitted and what the TX ID was when we submitted it. Will the coordinator share this information after the fact?
> 
> > I'm still curious about this bit though. Maybe it's in one of the other LLDs, it's very possible that I missed it.
> 
> Right sorry I missed this question. I do believe you could query this information from the node, but I also imagine the coordinator sending updates to the Deposit API (or Emily) as noted in this [LLD](https://docs.google.com/document/d/13AN9GdLfPYKKPkeHNU4niq_CyJCDxFR7DGBLzLc5gxU/).


👍🏽 I see. So the signers need to regularly query the node or Emily for this information? Perhaps right after the block observer informs them of a new block, since that will correspond to a new coordinator, and their state of any outstanding transactions will need to be synced.

**Comment by netrome** [comment]
> 👍🏽 I see. So the signers need to regularly query the node or Emily for this information? Perhaps right after the block observer informs them of a new block, since that will correspond to a new coordinator, and their state of any outstanding transactions will need to be synced.

Yeah, if the transaction has been included in a block we'd be able to observe it directly from the state populated by the block observer. But for status updates for pending transactions is best to query the mempool directly to know if a transactions is soon to be included in a block or needs RBF or whatnot.

**Comment by djordon** [comment]
Oh, I think we need to store the public key used for each of the signers' broadcasted UTXOs. We should also think about a strategy for storing their private key shares too but we may need a design for that.

**Comment by netrome** [comment]
> Oh, I think we need to store the public key used for each of the signers' broadcasted UTXOs. We should also think about a strategy for storing their private key shares too but we may need a design for that.

Their private key shares should be stored in the `dkg_shares` table. I don't quite follow what you mean by the "public key used for each of the signers' broadcasted UTXOs", isn't this just the aggregate public key of the signers?

**Comment by djordon** [comment]
> Their private key shares should be stored in the `dkg_shares` table. I don't quite follow what you mean by the "public key used for each of the signers' broadcasted UTXOs", isn't this just the aggregate public key of the signers?

Oh right I forgot we had this designed here 😄, sorry.

As for the "public key used for each of the signers' broadcasted UTXOs" I mean we should note which public key was used for each transaction in the case of key rotation. If a signer leaves or a new one gets onboarded we'll have a new public key, but all confirmed UTXOs may have been created using the old public key. So when we ask the signers to provide a signature for a UTXO, we should tell them which key was used to sign it.

**Comment by netrome** [comment]
> As for the "public key used for each of the signers' broadcasted UTXOs" I mean we should note which public key was used for each transaction in the case of key rotation. If a signer leaves or a new one gets onboarded we'll have a new public key, but all confirmed UTXOs may have been created using the old public key. So when we ask the signers to provide a signature for a UTXO, we should tell them which key was used to sign it.

Right, this is already explicit in the UTXO since the address of the UTXO is derived from the key. If you know the key, you can look up the address.

If we need to do the converse (go from address -> key) we could add a table for that lookup, but I'm not sure when we'd do that.

**Comment by netrome** [comment]
> > As for the "public key used for each of the signers' broadcasted UTXOs" I mean we should note which public key was used for each transaction in the case of key rotation. If a signer leaves or a new one gets onboarded we'll have a new public key, but all confirmed UTXOs may have been created using the old public key. So when we ask the signers to provide a signature for a UTXO, we should tell them which key was used to sign it.
> 
> Right, this is already explicit in the UTXO since the address of the UTXO is derived from the key. If you know the key, you can look up the address.
> 
> If we need to do the converse (go from address -> key) we could add a table for that lookup, but I'm not sure when we'd do that.

From a google meet we agreed that it makes sense for signers to be able to look up keys for a particular address to be able to know which key shares to use for a signing round. Since the signer UTXO address is the tweaked public key, we've updated the `dkg_shares` table to include this key alongside the untweaked aggregate key.

**Comment by netrome** [comment]
With these final changes, I'm closing this issue. We'll still naturally be able to extend the model as we go, but it seems we're aligned on the structure of it.
