### ISSUE TITLE
[Feature]: Get nakamoto start height from `/v2/pox` instead of config

### ISSUE THREAD

**Issue by cylewitruk** [stacks-network/sbtc#621]
# Feature - Get nakamoto start height from `/v2/pox` instead of config

## 1. Description

It turns out that we can get the epoch 3.0 (nakamoto) start height from the Stacks node's `/v2/pox` endpoint, instead of needing it to be specified in the config.

### 1.1 Context & Purpose
Requiring the nakamoto block height to be specified in config when we can get it from the node itself reduces the potential for someone messing around with this number and causing undefined behavior when wrong. It also makes it easier when testing as the sBTC signer will automatically use the nakamoto block height from the environment instead of the config needing to be updated.

## 2. Technical Details:
- Add a `StacksInteract` method for getting `PoxInfo`.
- Find an appropriate place at startup to read this information and make it globally available (somehow, maybe via the context).

### 2.1 Acceptance Criteria:
   - [ ] Nakamoto start height is read from the Stacks node instead of via config.

**Comment by djordon** [comment]
We've done this in https://github.com/stacks-network/sbtc/pull/1093, https://github.com/stacks-network/sbtc/pull/633, and https://github.com/stacks-network/sbtc/pull/772. The current state reads from config but will fall back to the stacks node if the config value is unset.
