### ISSUE TITLE
[Tech Debt]: Fix lack of integration tests for creating complete-deposit sign requests

### ISSUE THREAD

**Issue by AshtonStephens** [stacks-network/sbtc#631]
## Description

PR that introduced tech-debt:  #615

We didn't include integration tests for the feature in this ticket in order to sprint toward deposit flow demo. This ticket is to add integration tests.

**Comment by djordon** [comment]
Integration tests were added to https://github.com/stacks-network/sbtc/pull/615 before it was merged.
