### ISSUE TITLE
[Feat] - Inform the user once their deposit has been processed

### ISSUE THREAD

**Issue by setbern** [stacks-network/sbtc#658]
User story: User should not have to refresh the page in order to see the latest updates for it's transaction.

Create a basic polling logic to fetch the latest status of a deposit transaction from emily.

After submitting the deposit request the bridge should store the txId locally and refetch the status every 30 seconds. 

## Acceptance criteria

- As a user, after I issue a deposit transaction, I leave the website open and I eventually see a dynamic toast that informs me that the deposit has been completed.
- The toast is not going to go away unless I click on it.

**Comment by hozzjss** [comment]
Resolved in #938
