### ISSUE TITLE
[Feature]: Propagate broadcasted messages internally

### ISSUE THREAD

**Issue by djordon** [stacks-network/sbtc#667]
# Feature - Propagate broadcasted messages internally

## 1. Description

Each signer often needs to be a receiver of the very same messages that it broadcasts to peer signers in the peer-to-peer network. In particular, the `TxSignerEventLoop` and `TxCoordinatorEventLoop` tasks need to receive each others’ messages, even when they originate from the same signer process.

### 1.1 Context & Purpose

The two main examples where a message needs to be sent between two tasks within the same signer process are:

1. During distributed key generation (DKG), all `TxSignerEventLoop` tasks on the network need to communicate with the signer coordinator `TxCoordinatorEventLoop` task in order for DKG to succeed.
2. During signing of both Stacks and Bitcoin transactions, the `TxCoordinatorEventLoop` task does not add its own signature but instead relies on a majority of `TxSignerEventLoop` tasks sending in their signature shares. Since these tasks don’t talk within the same process, the signer coordinator never contributes it’s own signature share.

## 2. Technical Details:

The `TxCoordinatorEventLoop` and `TxSignerEventLoop` tasks need to receive all of each others’ broadcasted messages. In libp2p, the default behavior is that you do not receive your own messages, implying that the `TxCoordinatorEventLoop` and `TxSignerEventLoop` tasks don’t communicate in the way that they need to. During tests, we set things up so that all tasks communicate with one another, so this problem isn’t captured in our tests.

There does not appear to be a simple way in libp2p to change this behavior. The `Gossipsub` libp2p  type has an [`allow_self_origin`](https://docs.rs/libp2p/latest/libp2p/gossipsub/struct.ConfigBuilder.html#method.allow_self_origin) flag, but it is not quite what we want (it allows us to receive our own messages, but doesn’t guarantee that we do).

Lastly, we do not want the `TxCoordinatorEventLoop` or the `TxSignerEventLoop` tasks to receive their own messages.

### 2.1 Acceptance Criteria:

- [ ]  `TxCoordinatorEventLoop` and `TxSignerEventLoop` tasks receive each others’ messages in the when the `network` is the `P2PNetwork`.

## **Related Issues and Pull Requests (optional):**

**Comment by cylewitruk** [comment]
@djordon as it is right now the transaction coordinator doesn't process any received network messages, but it does receive the `TxSignerEvent::NewRequestsHandled` event and react on that -- is that what you were referring to regarding the coordinator?
