### ISSUE TITLE
[sBTC DR] Withdrawal Flow

### ISSUE THREAD

**Issue by stjepangolemac** [stacks-network/sbtc#68]
A set of functions that enables the handler to respond to new withdrawals, burn updates, fulfillment updates, and requesting broadcasting of new burn or fulfillment transactions.

It should be triggered by:

- new withdrawals
- burn status updates
- fulfillment status updates

It should be able to request these tasks:

- broadcast new burn transactions
- broadcast new fulfillment transactions

**Comment by netrome** [comment]
To make the withdrawal flow work with the bridge and be more future proof, we should look into these design issues:

https://github.com/stacks-network/sbtc-docs/issues/82
https://github.com/stacks-network/sbtc-docs/issues/31
