### ISSUE TITLE
[Feature]: Do not attempt to vote on requests more than once

### ISSUE THREAD

**Issue by djordon** [stacks-network/sbtc#684]
# Feature - Do not attempt to vote on requests more than once

## 1. Description

After a signer has voted on a deposit request, they don't need to vote again. Doing so can be costly so we should limit the vote attempts to deposit requests that are missing votes. Right now we continually vote on all deposit requests at each bitcoin block, indefinitely. The same thing is true for withdrawal requests.

### 1.1 Context & Purpose

The queries that fetch pending deposits and withdrawals do not filter out requests that the signer has voted on already. Update the `get_pending_deposit_requests` and `get_pending_withdrawal_requests` queries to do that filtering.

## 2. Technical Details:

Update the queries that get pending requests to accept the current signer's public key as input and exclude deposit requests where this signer has already voted. Each signer's vote on a deposit request is recorded in the `deposit_signers` table. 

### 2.1 Acceptance Criteria:
   - [ ] The `get_pending_deposit_requests` query returns only deposit requests that need the signer's vote.
   - [ ] The `get_pending_withdrawal_requests` query returns only withdrawal requests that need the signer's vote.

**Comment by aldur** [comment]
Pushing this out of sBTC deposit milestone, to be revised later.

**Comment by cylewitruk** [comment]
> Pushing this out of sBTC deposit milestone, to be revised later.

@aldur was this supposed to be removed from the milestone or did we decide after the fact to keep it?

**Comment by aldur** [comment]
Moved it to "sBTC release ready", thank you!

**Comment by djordon** [comment]
I'm pulling this one in to help us out with networking congestion issues on testnet.
