### ISSUE TITLE
[Design]: sBTC Signers Update the Emily API

### ISSUE THREAD

**Issue by AshtonStephens** [stacks-network/sbtc#687]
***Completing the issue description and arriving at a conclusion is the deliverable of this issue.***

# Design - sBTC Signers Update the Emily API

This ticket holds the design of the Emily sidecar and how it fits into sBTC-v1. Specifically, how the sBTC signers themselves would keep the Emily API up to date.

## 1. Summary

The Emily API needs to receive updates from some binary that has access to the Stacks Node. The sBTC signers already have access to the stacks node and will consume updates from an event observer. The alternative is to have a separate event observer with a different stacks node update the Emily API, but this seems to make less sense because it would require more nodes to be deployed and introduces a new binary that is important to maintaining the system.

## 2. Context & Purpose

The Emily API was originally designed to receive updates about the clarity contracts called on chain from a simple sidecar that we'd write and host on a number of nodes, but in addition to that there are some updates to the status of deposits and withdrawals that only the sBTC signers have the information to maintain. For example, only the sBTC signers will know if a deposit or withdrawal has been approved by enough signers but that that hasn't translated to an updated on chain yet.

We've realized that since the sBTC signers are going to be maintaining some aspects of the Emily API's state, it doesn't make much sense to have the signers responsible for some subset of the data and another piece of infrastructure maintain the rest, especially when the sBTC signers will already be hosting an event observer and node that has the information necessary to carry out these updates.

***Relevant Research Discussions***

***External Resources***

- Original API HLD, only slightly out of date: [link](https://docs.google.com/document/d/13AN9GdLfPYKKPkeHNU4niq_CyJCDxFR7DGBLzLc5gxU/edit#heading=h.ptdfh4l8o87r)

### 3.1 Proposed Component Design

The proposed design is to have the sBTC Signers maintain the state of the Emily API by sending simple updates to the Emily API by just relaying the information printed from the clarity contracts that maintain sBTC. For example, when the mint sBTC clarity contract executes it provides the following information:

- printed from clarity contract: [sbtc-registry.clar#L235-L236](https://github.com/stacks-network/sbtc/blob/f50e2918d97c47fddda3c38cf9d8c57fdd31aa5c/contracts/contracts/sbtc-registry.clar#L235-L236)
    - bitcoin-txid
    - bitcoin-output-index
- taken from stacks block data
    - stacks-block-hash
    - stacks-block-height 

In this example the sBTC signer would pick up this information from the event observer and then make a simple API call to update all deposits that received updates. Every sBTC Signer can do this at once and there should be no inconsistency error. In this example detecting this event would execute the following API call:

```
PUT
path: /deposits
body: {
  "deposits": [
    {
      "bitcoinTxOutputIndex": 1,
      "bitcoinTxid": "bitcoin_txid",
      "lastUpdateBlockHash": "hash",
      "lastUpdateHeight": 123,
      "status": "confirmed",
      "statusMessage": "confirmed."
    }
  ]
}
```

See the original API HLD for details: [link](https://docs.google.com/document/d/13AN9GdLfPYKKPkeHNU4niq_CyJCDxFR7DGBLzLc5gxU/edit#heading=h.ptdfh4l8o87r)

### 3.1.1 Design Diagram

Details in the HLD linked above.

### 3.1.2 Considerations & Alternatives

Alternatively we could have a separate binary maintain the state but doing this means there's more infrastructure required for the final release, there's more code that needs to be written to listen to events, and that there's another place for infrastructure to falter. The sBTC Signers are necessary to maintain the protocol and must also have at least one of them connect to the Emily API in order to detect pending deposits, so requiring the connect to the Emily API isn't anything new.

### 3.2 Areas of Ambiguity

- What happens if there's a connection error?
   - Suggestion: Ignore it and follow through, one of the signers will maintain it
 
---

**Closing Checklist**
- [x] The design proposed in this issue is clearly documented in the description of this ticket.
- [ ] Everyone necessary has reviewed the resolution and agrees with the proposal.
- [ ] This ticket has or links all the information necessary to familiarize a contributor with the design decision, why it was made, and how it'll be included.

**Comment by AshtonStephens** [comment]
In progress

**Comment by djordon** [comment]
No. We shouldn't
