### ISSUE TITLE
[Feature]: Emit print events after we successfully rotate-keys

### ISSUE THREAD

**Issue by djordon** [stacks-network/sbtc#689]
# Feature - Emit print events after we successfully rotate-keys

## 1. Description

We emit events after we've successfully executed almost all sBTC contract calls, the one exception is the `rotate-keys` contract call. We should emit such an event for the signers to consume. This has two benefits:
1. It allows other developers to watch for these events and use the new aggregate public key for depositing BTC into sBTC.
2. It simplifies the logic required in the signers for handling key rotation transactions.

## 2. Technical Details:

Add a print event to the end of the `rotate-keys` public function with a tuple fields for all inputs into the public function.

### 2.1 Acceptance Criteria:
   - [ ] We emit a print event at the end of the `rotate-keys` function in the registry.
   - [ ] The signers note pick up this event and store it in the database.

**Comment by setzeus** [comment]
Was able to get most of this done including a test with the exception of a single field: "new-address." This is a Clarity-specific multi-sig that's calculated at run-time. Working on getting this last element fixed then should be good for review.
