### ISSUE TITLE
[Feature]: Address invalid Schnorr signature error

### ISSUE THREAD

**Issue by djordon** [stacks-network/sbtc#690]
# Feature - Address invalid Schnorr signature error

## 1. Description

During the pre-demo, we sometimes got an error from bitcoin-core rejecting the transaction with the error message `"non-mandatory-script-verify-flag (Invalid Schnorr signature)"`. This happens randomly during our tests, but it appears to depend on the parity of the aggregate key.

### 1.1 Context & Purpose

Well, we cannot be a bridge if we cannot always sign for the transactions that we are supposed to sign for.

## 2. Technical Details:

Figure out the cause of the issue and solve it. Find a way.

### 2.1 Acceptance Criteria:
   - [ ] The signers never get that error from bitcoin core for their transactions.

**Comment by xoloki** [comment]
I found the problem: `WSTS` does not implement the correct `BIP-341` algorithm for computing a tweaked public key.  There is a parity check involved which is skipped, so when we interpolate then tweak the private key during signing we end up with a mismatch between public and private keys, but only if the original public key had odd parity.

I'll address this in the current `WSTS` PR https://github.com/Trust-Machines/wsts/pull/94

**Comment by djordon** [comment]
> I found the problem: `WSTS` does not implement the correct `BIP-341` algorithm for computing a tweaked public key. There is a parity check involved which is skipped, so when we interpolate then tweak the private key during signing we end up with a mismatch between public and private keys, but only if the original public key had odd parity.
> 
> I'll address this in the current `WSTS` PR [Trust-Machines/wsts#94](https://github.com/Trust-Machines/wsts/pull/94)

This is great news! Perfect, I'll watch for the change in that PR.

**Comment by xoloki** [comment]
The `sign_bitcoin_transaction` integration test now passes when built against the `simple-signature-type` branch of `wsts`.
