### ISSUE TITLE
Stacks address construction improvement

### ISSUE THREAD

**Issue by stjepangolemac** [stacks-network/sbtc#7]
At the moment `StacksAddress` from `stacks-core` has the same approach to construction as its `blockstack-lib` counterpart. It uses a single `from_public_keys()` function that has a lot of ambiguous arguments - in order to support all address types.

I propose breaking this down into multiple constructors that will make address construction more clear both in terms of type and corresponding arguments.

```
StacksAddress::p2pkh(pk: &PublicKey)
StacksAddress::p2sh(num_sigs: usize, pub_keys: &[PublicKey])
...
```

There's also the opportunity to use better types for arguments and make them more flexible, such as `impl Iterator<Item = &PublicKey>`.

**Comment by stjepangolemac** [comment]
@netrome what do you think?

**Comment by netrome** [comment]
@stjepangolemac I added this to the "Stacks Core Eng" project. I recommend doing so and it will be visible on the sBTC board.
https://github.com/orgs/stacks-network/projects/63/views/14
