### ISSUE TITLE
[Feat] - Detail view for Deposit upgrades

### ISSUE THREAD

**Issue by setbern** [stacks-network/sbtc#704]
Update the tx status view based on Emily, and RPC tx status.

View should also show the steps needed to go through at a high level for a complete deposit.

Completed when
- Views are built out from the figma
- Emily API, Bitcoin RPC & stx api are hooked up to ensure we have the latest status of the status

**Comment by aldur** [comment]
Note for our future selves: this was scoped as a size 2 but it was probably bigger and would have required splitting it up.

**Comment by aldur** [comment]
Closing this as code is on `main` and locking the `main` branch to require PRs going forward on https://github.com/stacks-network/sbtc-bridge.
