### ISSUE TITLE
[Tech Debt]: Fix DepositUpdate in handle_completed_deposit to contain the exact `btc_fee`

### ISSUE THREAD

**Issue by Jiloc** [stacks-network/sbtc#722]
## Description

PR that introduced tech-debt: #712

When we create `DepositUpdate` messages for Emily to update the deposit to `Confirmed`, we are currently hardcoding the [paid btc fee to 1](https://github.com/stacks-network/sbtc/blob/332e042e9881f3135152d5755934aeeb51dba094/signer/src/api/new_block.rs#L271). 

There could be multiple ways to extract the fee. One clean way could be to modify the [`complete-deposit`](https://github.com/stacks-network/sbtc/blob/main/contracts/contracts/sbtc-registry.clar#L233) function in the `sbtc-registry` contract to also print this information exactly like the [`complete-withdrawal-accept`](https://github.com/stacks-network/sbtc/blob/main/contracts/contracts/sbtc-registry.clar#L184) function event does.

This way we could simply read the value from the print event like we do [when we construct a `WithdrawalUpdate`](https://github.com/stacks-network/sbtc/blob/332e042e9881f3135152d5755934aeeb51dba094/signer/src/api/new_block.rs#L312)

**Comment by djordon** [comment]
I see, so we should update this when we do https://github.com/stacks-network/sbtc/issues/583.

**Comment by aldur** [comment]
Thank you! As discussed, moved this to https://github.com/stacks-network/sbtc/milestone/12.

**Comment by djordon** [comment]
I think that it's useful to think about this ticket out as two separate issues:
1. Making sure that the real `btc_fee` fee is sent to Emily.
2. Adding the `btc_fee` to the clarity contract for `complete-deposit` contract calls.

We can and should do (1) now. A signer can compute the fee using the information in the `complete-deposit` event and the original deposit request UTXO. If a signer does not have the deposit request record in their database then it just shouldn't bother updating Emily. We can figure out whether we should do (2) later.
