### ISSUE TITLE
[Feature]: Emily client authentication

### ISSUE THREAD

**Issue by cylewitruk** [stacks-network/sbtc#748]
# Feature - Emily client authentication

## 1. Description

The Emily API has some protected endpoints and we currently do not support initializing the Emily client with authentication information. This needs to be done to secure the protected endpoints from tampering from non-signers.

## 2. Technical Details:

The API credentials should be configurable in the config, and these credentials should be used for the relevant Emily API calls.

**Comment by AshtonStephens** [comment]
I'll do this one; I'll need to spin up dev infrastructure to test this so it'll go after #692

**Comment by aldur** [comment]
Note: just marked this as "high" since it is required for client-side authentication.
