### ISSUE TITLE
[Feature]: Store bitcoin block anchoring Stacks blocks

### ISSUE THREAD

**Issue by djordon** [stacks-network/sbtc#754]
# Feature - Store bitcoin block anchoring Stacks blocks

## 1. Description

Before we write stacks blocks to the database we fetch the bitcoin block that anchors the Stacks block and we write that to the database. But we do not check for whether we know about that bitcoin block at all. It's possible that we don't.

I don't think this is a critical issue though since the signers all follow their bitcoin node for blockchain information. If a Stacks block is anchored to a block that is not on the canonical bitcoin blockchain then we will ignore it anyway.

## 2. Technical Details:

Store the anchor bitcoin block in the database if we do not have a record of it before writing the Stacks block to the database.

### 2.1 Acceptance Criteria:
   - [ ] We always have a record of the anchor bitcoin block in our database for each Stacks block.

## 3. Related Issues and Pull Requests (optional):

This looks similar to https://github.com/stacks-network/sbtc/issues/731, since they'll use the same code.

**Comment by aldur** [comment]
To be investigated on whether it is a requirement (e.g. critical bug) or a nice to have.

**Comment by djordon** [comment]
I no longer think that this is necessary, closing.

---
## Details

The underlying issue is that we don't want there to be a case where the anchor block is not in the database when we want to find relevant Stacks transactions or events. But the signers only care about transactions/events when they are on the canonical chain(s), and the signers try to maintain an up-to-date view of the canonical chain so this issue is moot.
