### ISSUE TITLE
[Feature] - Ensure user is able to edit max fee from. good UX pov

### ISSUE THREAD

**Issue by setbern** [stacks-network/sbtc#776]
Right now the max fee starts at 80,000 sats, the user is able to set this fee manually.

In production we'll need to estimate the max fee for the user and then suggest it.

If the user chooses to set their own max fee we must allow that flexibility.

## Acceptance criteria:

- As a user, the bridge suggests a fee that I should be paying.
- I can override that fee if I believe so.

**Comment by aldur** [comment]
Integration with wallets makes this not required anymore.
