### ISSUE TITLE
[Chore]: Production docker compose

### ISSUE THREAD

**Issue by AshtonStephens** [stacks-network/sbtc#785]
# Chore - Production docker compose 

## 1. Description

Create a docker compose that spins up all the necessary containers for a signer to run sBTC in production.

## 2. Why It's Necessary

People running signers need to be able to spin up the infrastructure quickly and smoothly. This GitHub issue is to make the docker compose that sets all the entities up.

## 3. Execution Checklist

- [ ] Create a docker compose that can run all the necessary production infrastructure
- [ ] Have that docker compose in a PR and merged

**Comment by AshtonStephens** [comment]
@aldur what do we envision to be the immediate purpose of this docker compose? Is this to give people an idea of what's necessary or be exactly what they anticipate using in prod?

Additionally, I'd like to propose that we don't include a stacks node in this, and we expect them to have that already running so we separate this compose from any changes made to the stacks core images. WDYT?

**Comment by aldur** [comment]
> @aldur what do we envision to be the immediate purpose of this docker compose? Is this to give people an idea of what's necessary or be exactly what they anticipate using in prod?

Let's assume that signers will use this either verbatim or as a base (e.g., if deploying through K8).

> Additionally, I'd like to propose that we don't include a stacks node in this, and we expect them to have that already running so we separate this compose from any changes made to the stacks core images. WDYT?

I agree. Would it be feasible for signers that are not already running their node to rely on a node provider?
