### ISSUE TITLE
[sBTC DR] Assert deposit/witdhdrawal tx exists in mint/burn contract calls

### ISSUE THREAD

**Issue by netrome** [stacks-network/sbtc#79]
### Definition of done
The sBTC DR asset contract does not allow mints and burns that do not refer to existing bitcoin transactions

**Comment by MarvinJanssen** [comment]
How was the interface decided? #78 mentioned "[...] We just maintain the right interface [...]". Is this "right interface" intended to only be for Romeo or beyond? I understood that for Romeo we want to define an interface that is stable.

If that is the case, we need to work closely on defining that interface.

I can take on this task but I need to know the exact requirements. We have all the logic to check if a Bitcoin transaction is mined. It just needs to be moved over and adapted.

**Comment by netrome** [comment]
> How was the interface decided? #78 mentioned "[...] We just maintain the right interface [...]". Is this "right interface" intended to only be for Romeo or beyond? I understood that for Romeo we want to define an interface that is stable.
> 
> If that is the case, we need to work closely on defining that interface.
> 
> I can take on this task but I need to know the exact requirements. We have all the logic to check if a Bitcoin transaction is mined. It just needs to be moved over and adapted.

Good questions @MarvinJanssen . We kept the same interface to the `mint` and `burn` calls from the previous alpha work, where both of them takes a transaction ID and a principal as input. If you anticipate that we need other things in the interface, this is a good time to update it or redefine it, but to the best of my knowledge that is the only information the mint and burn calls will need after the consensus breaking release as well.

Two additional points to keep in mind as well:
1. The interface is in no way frozen and we will update it as we discover new things, as long as we maintain parity between Nakamoto sBTC and DR sBTC.
2. The `mint!` and `burn!` function signatures are not user-facing which gives us more flexibility to update them in the future. However, users/developers may rely on events emitted from them so we should be more careful about those.

**Comment by friedger** [comment]
To verify that a tx exists the contract needs a block height, raw tx,... up to 10 parameters as described in https://clarity-bitcoin.gitbook.io/clarity-bitcoin-library/clarity-functions

Can we expect a certain format of the btc transactions? @netrome 
Are they always segwit txs? Always N inputs and M outputs?

**Comment by netrome** [comment]
> To verify that a tx exists the contract needs a block height, raw tx,... up to 10 parameters as described in https://clarity-bitcoin.gitbook.io/clarity-bitcoin-library/clarity-functions
> 
> Can we expect a certain format of the btc transactions? @netrome Are they always segwit txs? Always N inputs and M outputs?

Thank you for linking the clarity-bitcoin-library docs. Unfortunately the requirements sound much more complex than I expected. I was under the impression that there existed some simple function to assert that a transaction had been mined given just a single txid.

We cannot expect an exact format of the btc transactions. They can consume both segwit and normal inputs, and have variable number of outputs. Moreover, I see we need to provide a block header and a merkle proof. Are these pure functions or do they actually look up the bitcoin chain to find if the block exists? We don't need to validate the transaction, we just need to assert that the txid exists on the canonical bitcoin fork.

Would `was-tx-mined` still return true if we provided information from a block which does not exist on the canonical bitcoin fork?

In either case, the problem is only specific to the developer release and doesn't exist in sBTC 1.0 - so if it's not trivial I suggest not doing this.

**Comment by friedger** [comment]
Getting all the data includes some simple lookups on the bitcoin chain and calculations to bring the data into the correct format, see for example https://github.com/friedger/clarity-bitcoin/blob/main/src/generatePlan.ts#L16 

Clarity VM only looks up the block header hash. Therefore, `was-tx-mind` will return false if the provided data does not match the data on the current bitcoin network (from the view of the stacks node).

For stacks in general, it would be good to have tools that can create the arguments for `was-tx-mined` or `was-segwit-tx-mined`. Therefore, I suggest to do it. @kenrogers would be interested as well.

**Comment by friedger** [comment]
The clarity part is assigned to @MarvinJanssen

**Comment by friedger** [comment]
A simpler solution than `was-tx-mined` would be to just provide the block height and header hash and verify only that in clarity. It would ensure in a similar way that the bitcoin block containing the tx is visible to the stacks chain. @MarvinJanssen
