### ISSUE TITLE
[sBTC DR] Containerize and deploy developer release

### ISSUE THREAD

**Issue by netrome** [stacks-network/sbtc#85]
Once the sBTC DR deposit and withdrawal flows are implemented, we should make it easy for anyone to spin up a docker deployment of the developer release. In addition, we also want to run a hosted version within TrustMachines (or any other organization) infrastructure to allow developers to test their sBTC integrations without self-hosting a dev-release.

### Definition of done
We have a `Dockerfile` in the repo for building a containerized version of the dev release. A docker image is published and documented in the sBTC docs. The docs are also updated to point to the deployed contract.

**Comment by friedger** [comment]
I am happily using clarinet integrate. Is that not good enough?

**Comment by friedger** [comment]
How is this related to https://github.com/stacks-network/sbtc/issues/11
