### ISSUE TITLE
[sBTC DR] Improve asset contract

### ISSUE THREAD

**Issue by friedger** [stacks-network/sbtc#89]
**Bug**
1. The current supply is defined as 21_000_000, that is equivalent to 0.21 BTC. 
2. The current token-uri refers to a PDF.

**Expected Behaviour**
1. Define supply as 21_000_000_00_000_000.
2. Link to a json with meta data according to [SIP-16](https://github.com/stacksgov/sips/blob/main/sips/sip-016/sip-016-token-metadata.md). Simple example AutoAlex-v2: https://cdn.alexlab.co/metadata/token-auto-alex-v2.json

**Comment by friedger** [comment]
Can you assign it to me

**Comment by setzeus** [comment]
Assigning myself here, fixed the supply issue & think I see an unnecessary optional with the bitcoin-wallet-public-key var?

The only update/write function requires a (public-key (buff 33)) input so it can't be set to none as is.

**Comment by friedger** [comment]
Main task is to host a good json with metadata

**Comment by friedger** [comment]
Fixed by #112
