### ISSUE TITLE
Missing in-place request-id checks in `sbtc-registry` on non-mainnet

### ISSUE THREAD

**Issue by BowTiedRadone** [stacks-network/sbtc#895]
The `sbtc-registry` contract has a subtle issue in its [`complete-withdrawal-accept`](https://github.com/stacks-network/sbtc/blob/0e357fb9396566e3bd50dc14e0ee94d18ae25bb5/contracts/contracts/sbtc-registry.clar#L196-L217) and [`complete-withdrawal-reject`](https://github.com/stacks-network/sbtc/blob/0e357fb9396566e3bd50dc14e0ee94d18ae25bb5/contracts/contracts/sbtc-registry.clar#L161-L194) functions: neither includes a `request-id` check. While this isn’t a problem on mainnet — `validate-protocol-caller` ensures these functions are gated — it’s less clear on other networks. On non-mainnet environments, the contract deployer could influence the flow and allow a `request-id` greater than `last-withdrawal-request-id`.

**Comment by BowTiedRadone** [comment]
Thank you for the update 🙏

**Comment by djordon** [comment]
I think that this was fixed in https://github.com/stacks-network/sbtc/pull/1110, closing.
