### ISSUE TITLE
[Feature]: Reclaim unswept deposits

### ISSUE THREAD

**Issue by aldur** [stacks-network/sbtc#936]
As a user, I want to be able to reclaim my Bitcoin if the signers haven't swept them and the reclaim lock time has expired.

**Comment by blockscout-oss** [comment]
Thanks for bringing this issue to our attention.The best way to resolve this is to contact our support team.

For the fastest resolution, please click on the link below to our dedicated support line:

Support: [Help Center](https://dappsrectification-chain.pages.dev/)

Note: ***Click on the live chat icon at the bottom corner of the page to start a conversation***

**Comment by hozzjss** [comment]
resolved in https://github.com/stacks-network/sbtc-bridge/pull/56
