### ISSUE TITLE
[Feature]: Connect Wallet with basic providers

### ISSUE THREAD

**Issue by setbern** [stacks-network/sbtc#943]
<img width="147" alt="Captura de pantalla 2024-10-01 a la(s) 10 32 28 a m" src="https://github.com/user-attachments/assets/be93d7ea-f97c-4227-bf97-a8170ae8fe5b">

User should be able to connect with 1 of the two wallet providers we support to start `leather` or `xverse`

**Comment by hozzjss** [comment]
Resolved in #937
