### ISSUE TITLE
[Feature]: Add configuration for signing round & dkg max durations

### ISSUE THREAD

**Issue by cylewitruk** [stacks-network/sbtc#947]
# Feature - Add configuration for signing round & dkg max durations

## 1. Description

We have the following values hardcoded in `main.rs` which are used as inputs to the transaction coordinator and signer. These should be configurable so that they can be changed if needed without a new deploy.

- `signing_round_max_duration` (coord)
- `dkg_max_duration` (coord)
- `dkg_begin_pause` (signer) - _this may be deprecated by upcoming dkg changes_

### 2.1 Acceptance Criteria:
   - [ ] The max signing round duration can be configured and the value is respected in the coordinator
   - [ ] The max DKG duration can be configured and the value is respected in the coordinator.
   - [ ] A DKG-begin pause can be configured and the value is respected in the signer.

**Comment by djordon** [comment]
This was fixed in https://github.com/stacks-network/sbtc/pull/1014, with the pause parameter added in https://github.com/stacks-network/sbtc/pull/1019.
