### ISSUE TITLE
Integration tests using devenv

### ISSUE THREAD

**Issue by CAGS295** [stacks-network/sbtc#95]
### Goal
---
To Showcase how rust integration tests could work with `devenv` and `nextest` as the main drivers.

### Why
---
We need integration tests for an sBTC node in CI.

### Glossary
- **full sBTC node**: A bundle of binaries that provide all the features needed for sBTC to progress and provide inspection.
- **devenv** a bundle of scripts and docker files to manage a docker-compose project for local sBTC development.
- **runner** a container instance of `docker run <image>` running a group of tests.
- **nextest** is a rust test runner that allows us to parallelize integration test runs.

### Overview.

`Devenv` uses `docker compose` to spin a full sBTC node for local development. A container with integration tests can execute them against the node by sharing its network. This approach requires very little handling from within the tests. We can spin multiple instances of the same services using different project names and assign each to an integration test runner. The runner internally uses Nextest as the test harness to run tests. To use the assigned node within Rust, tests must resolve the service's address, that is it. The runner is passed an environment variable with the project name to resolve to the services' address.

We employ two forms of parallelism to speed things up. First, we use test filters to bundle tests into groups that can run under the same node instance. These tests must be independent of each other and not cross-contaminate. Second, testing groups run in parallel. There is a 1o1 relationship between the node instance, tests group, and runner.
We wait for the exit code for each node and runner executed in parallel. If any runner exits with an error, we fetch the failing runner logs, print them, and propagate the error.

### Modeled example.

The source code can be found in [this](https://github.com/CAGS295/sbtc/tree/dev/test-service2) branch. 

There are integration tests scattered in a repo. We want to use the local `devenv` to run them all. We will pretend that the unit tests in this repo are integration tests. It does not matter; the use case is the same. The only prerequisite is that the node services are available for the tests.

We need a container to run the tests in; this container has the source code and the prebuilt tests ready to run.
An entry script has checks to wait until the node is 'deemed' ready so that it does not have to be checked in the tests.
I added basic checks to the demo. The Stacks RPC is responsive and returns that a given burn block height has been reached. Once all checks are passed, we can ensure the tests are ready to run. We call nextest to run our precompiled tests. The script executes `cargo nextest run -E "$@"` passing a filtering expression. Each filtering expression corresponds to a test group.

The testing script is where the grouping and parallel running happen. This is also the entry point for the testing pipeline (once you have built the images). The script is in charge of the following;

- start a new docker-compose project and its network for each filter group. Filters are an array of nextest's filter DSL.
```bash
filters=("package(romeo)" "test(deposit_parse)" "test(deposit_output)")
project=$(project_name $filter)
#...snip
./tests/bin/down docker-compose.yml $project
./tests/bin/up docker-compose.yml $project
```
- for each node, run the tests that match its filter in parallel.
```bash
$(docker run -td --network $network -e PROJECT_NAME=$project testbed "$filter")
```
- repeat for all groups (filters). If you want to isolate a test-per-node. Use a filter to 'exactly' match it.
- join all filters and find the complement. (any test not previously run at this point).
- run the remaining tests as a 'remainder' group.
- use `docker wait` to wait for the runners to exit. `docker run -d` will return an id. Store them. if a group exits with a non-zero, fetch the logs and exit.
```bash
for id in ${ids[@]}; do
    exit_code=$(docker wait $id)
    echo Runner: $id exited with err_no: $exit_code
    if [ $exit_code -ne 0 ]; then
        docker logs -f $id
        exit $exit_code
    fi
done
```
- if everything went well, take down all the nodes. In CI, an early exit is acceptable; locally, the nodes will dangle until taken down manually. I won't address this because it is easy to `docker stop $(docker ps -q)` them.

### Conclusions
---
This is the simplest yet complete example I could devise to parallelize and run integration tests that would not be a pain either locally or CI. You can reuse `devenv` to drive your integration tests. As long as you can use 'cargo test' to run your tests, you are good to go. You write your tests in native rust without worrying about externalities.

### Appendix
---
`devenv/tests/docker/Dockerfile`
```bash
#testbed image; compile and prebuild the workspace.
FROM rust:alpine
RUN apk add --no-cache g++ musl-dev git openssl-dev clang-dev libsecp256k1-dev
RUN rustup component add rustfmt
ENV RUSTFLAGS "-C target-feature=-crt-static"
RUN cargo install cargo-nextest --locked
COPY . .
RUN cargo nextest list
RUN apk --no-cache add curl jq
COPY ./devenv/tests/docker/entrypoint /bin/entrypoint
ENTRYPOINT [ "entrypoint" ]
```
`devenv/tests/bin/test`
```bash
#this is what you need to call in CI/dev to check that your tests pass.
project_name() {
    local input="$1"
    local filter="${input//[![:alnum:]]/_}"
    echo "$filter"
}

filters=("package(romeo)" "test(deposit_parse)" "test(deposit_output)")
filter_union=""
ids=()
projects=()

for filter in "${filters[@]}"; do
    project=$(project_name $filter)
    echo Working project: $project
    projects+=($project)

    ./tests/bin/down docker-compose.yml $project
    ./tests/bin/up docker-compose.yml $project

    network=${project}_default
    id=$(docker run -td --network $network -e PROJECT_NAME=$project testbed "$filter")
    ids+=($id)
    echo with container id: $id

    if [ -z "$filter_union" ]; then
        filter_union=$filter
    else
        filter_union="$filter_union | $filter"
    fi

done

project="remainder--"
echo Working project: $project
projects+=($project)

./tests/bin/down docker-compose.yml $project
./tests/bin/up docker-compose.yml $project

network=${project}_default
id=($(docker run -itd --network $network -e PROJECT_NAME=$project testbed "not ($filter_union)"))
ids+=($id)
echo with container id: $id

for id in ${ids[@]}; do
    exit_code=$(docker wait $id)
    echo Runner: $id exited with err_no: $exit_code
    if [ $exit_code -ne 0 ]; then
        docker logs -f $id
        exit $exit_code
    fi
done

for project in ${projects[@]}; do
    ./tests/bin/down docker-compose.yml $project
done
```
`devenv/tests/docker/entrypoint`
```bash
#the actual entrypoint in the container
#!/usr/bin/env sh
set -ueo >/dev/null

STACKS=$PROJECT_NAME-stacks-1
API_URL=http://$STACKS:20443/v2/info

# makes sure the node is ready before proceeding
# stacks node get info
echo "Waiting on Stacks API"
while ! curl -s $API_URL >/dev/null; do
    sleep 1
done

DEV_READY_HEIGHT=205

# bitcoind get info
echo "Waiting on burn block height $DEV_READY_HEIGHT"
while [ "$(curl -s $API_URL | jq '.burn_block_height')" -lt $DEV_READY_HEIGHT ]; do
    sleep 2
done
# any other service checks

echo with filter: "'$@'"
cargo nextest run -E "$@"
```

**Comment by CAGS295** [comment]
@AshtonStephens wdyt?

**Comment by CAGS295** [comment]
@jferrant @stjepangolemac @friedger fyi

**Comment by friedger** [comment]
What is a typical test in rust? Don't we want tests in clarity?

**Comment by CAGS295** [comment]
Quating @netrome from #11 
> I think we could repurpose this one. I'd like to have good integration testing for the new developer release as well. The happy path would be:
> 1. A user creates a deposit request https://stacks-network.github.io/sbtc-docs/sbtc-operations/bitcoin-transactions.html
> 2. The sBTC DR system mints the requested amount of sBTC to the users account.
> 3. The user creates a withdrawal request
> 4. The sBTC DR system burns the requested amount of sBTC from the users account.
> 5. Upon a successful burn, the system then fulfills the withdrawal request by transferring the requested amount of BTC back to the users account.

My partial understanding goes as follows.

Interacting with sBTC happens mainly using CLIs; bitcoin's and sBTC's. Rust devs want to write tests that closely resemble their dev experience and the user flow. Take your script as an example.

Ignoring contract deployment and empty block mining (`generateToAdrres`), the flow is sbtc-cli calls backed by romeo's rust library. If you use romeo's bitcoin-client to mine empty blocks instead, your flow can be implemented as an integration test in Rust. I assume complex workflows like #107 can also be modeled. This way, a rust dev does not need to relearn and 'port' sBTC knowledge to a different stack (e.g., clarity + clarinet + devnetJS) just for testing's sake. However, I'm starting to see heavy use of bash scripts, so I'd like to know if the team would prefer bash tests instead of rust integration tests altogether.

```
cd devnet
./up.sh

cd sbtc
./down.sh

cd ../..
cd romeo/asset-contract
clarinet deployments apply -p deployments/default.devnet-plan.yaml 

# wait

cargo run -p romeo -- --config-file romeo/testing/config.json


cargo run -p sbtc-cli -- generate-from -s testnet -b regtest mnemonic "twice kind fence tip hidden tilt action fragile skin nothing glory cousin green tomorrow spring wrist shed math olympic multiply hip blue scout claw" 

bitcoin-cli -regtest -rpcuser=devnet -rpcpassword=devnet -rpcport=18443 --rpcwallet="devnet" generatetoaddress 150 bcrt1q3tj2fr9scwmcw3rq5m6jslva65f2rqjxfrjz47

bitcoin-cli -regtest -rpcuser=devnet -rpcpassword=devnet -rpcport=18443 --rpcwallet="devnet" generatetoaddress 150 mqVnk6NPRdhntvfm4hh9vvjiRkFDUuSYsH

cargo run -p sbtc-cli -- deposit -w cTyHitzs3VRnNxrpwxo3fXTTe569wHNUs57tQM7Z1FrzUDNB5mqm -n regtest -r ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM -a 1000 -d bcrt1pte5zmd7qzj4hdu45lh9mmdm0nwq3z35pwnxmzkwld6y0a8g83nnqhj6vc0 -u localhost:60401

cargo run -p sbtc-cli -- broadcast localhost:60401 01000000000101010da73321be48f30562e44ff379ea981e204a4fa4bc859c6cd99418e705c7390000000000feffffff0300000000000000001b6a1969643c051a6d78de7b0625dfbfc16c3a8a5735f6dc3dc3f2cee8030000000000002251205e682db7c014ab76f2b4fdcbbdb76f9b8111468174cdb159df6e88fe9d078ce6ab040000000000001600148ae4a48cb0c3b7874460a6f5287d9dd512a182460247304402206387c555478eb821311ef4d3b125a8b4beb698be624e186ff6234f6cd1deb75702207cf063c9cd57dcd7c34b9477129a3a70403856a46be7b9e8942d79482b246379012103ab37f5b606931d7828855affe75199d952bc6174b4a23861b7ac94132210508cc10d0000
```

**Comment by friedger** [comment]
Makes sense and the proposed solution looks good to me. I don't mind using rust for testing.

**Comment by stjepangolemac** [comment]
In general this looks good. When it comes to bash scripts I'm not against them. I guess it depends on the scope of the test. If you're testing something internal to romeo, and you only need access to a stx/btc node, then I guess it makes sense to write a test in Rust. If you're testing the whole thing with all the components then Bash is fine.

One option for a path forward is to write some tests in bash and then see what is done the most. Then we can write a tiny Rust wrapper that does similar things. I suppose bulk of the work is just requesting and getting a pristine devnet environment.

**Comment by CAGS295** [comment]
> One option for a path forward is to write some tests in bash and then see what is done the most. Then, we can write a tiny Rust wrapper that does similar things. I suppose bulk of the work is just requesting and getting a pristine devnet environment.

I could take it from there. Side not, I would rather stay away from bash tests right now, just because my brain screams 'just use rust' and it hurts. But if people push the motion, I'll do it. Back to the main topic, I'll be happy to write a test in rust or bash if you have an integration scenario.

**Comment by CAGS295** [comment]
Leave LGTM to move forward, or suggest improvements. I want to close this already.

**Comment by AshtonStephens** [comment]
LGTM ~

**Comment by AshtonStephens** [comment]
Closing - it's done.

**Comment by friedger** [comment]
@AshtonStephens how do I run integration test? Is there a script that does a deposit and withdrawal? Or is the acceptance criterion that we can do manual testing?

**Comment by CAGS295** [comment]
The latter. The branch shows it is possible and how to do it. If you want to implement an integration test. 1. build a container to run the tests. Create an entry point with 'devnet is ready' checks. And then let the cargo test harness run your tests. Use filters to control 'node scheduling.' If you have a rust test, I can help you set it up.

**Comment by friedger** [comment]
@CAGS295 how would the rust test look like? I would like to deposit and withdraw and assert the amount of bitcoin.

The rust test would be a main program that does some http requests to the nodes?

**Comment by CAGS295** [comment]
[This](https://doc.rust-lang.org/rust-by-example/testing/integration_testing.html) how you generally want your integration tests to look.

Notice how in the entry point script. There is a pattern on how to build service's addresses. It is <project name>-<service>-1.

```
STACKS=$PROJECT_NAME-stacks-1
API_URL=http://$STACKS:20443/v2/info
```

The Project name is the filter after this transformation.

```
project_name() {
    local input="$1"
    local filter="${input//[![:alnum:]]/_}"
    echo "$filter"
}
```

 If you need to allocate a full-node for the withdrawal test, add it to the filter array, or it will be run bundled with everything. That is gonna be good enough for the first test. But you can expect cross-contamination if you add a second one. 

filters=("package(romeo)" "test(deposit_parse)" "test(deposit_output)")

```
filters=("package(romeo)" "test(deposit_parse)" "test(deposit_output)")
```

As an example, the array above will create four nodes. First, running all unit and integration tests under the romeo package. Second, every test in the repo matching 'deposit_parse.' Third, all that match 'deposit_output' and any remaining tests not run previously. Filters are in nextest's DSL.

I expect your test to look exactly like a bash script doing the steps with the cli's but using romeo and the bitcoin client as a library. Give it a go. I will start implementing integration tests tomorrow.

Don't forget to build the container `devenv/tests/bin/build` and add any binary you plan to use during your tests. You must add the bitcoin-cli if you plan to use it in the entrypoint script. Also, modify the entry point script to include any checks before running the tests. I assume you must add something to check for Romeo's availability.

The branch itself is not ready in a plug-and-play fashion. It works to showcase running unit tests as if they were integration tests. If it is too complicated, you can focus on making it work in a bash script and I'll port it to the devenv.
Oh yeah, I haven't added contract deployment using clarinet, you will have to add that in the entry point script. Clarinet/develop has a new flag to skip the input confirmation prompt. Don't forget to use it.
