### ISSUE TITLE
[Tech Debt]: Port `BitcoinPreSignRequest` to Protobuf

### ISSUE THREAD

**Issue by Jiloc** [stacks-network/sbtc#955]
## Description

PR that introduced tech-debt: #954 

In #954, we introduced a new message, `BitcoinPreSignRequest`, to facilitate the transfer of sBTC request data from the coordinator to the signers. This message is used for creating and validating the proposed transaction sighashes.

In PR #878, all messages were migrated to protobuf, leaving `BitcoinPreSignRequest` as the only message not yet ported.

**Comment by djordon** [comment]
This was closed in https://github.com/stacks-network/sbtc/pull/880
