### ISSUE TITLE
[Chore]: Slow query: `get_swept_deposit_requests`

### ISSUE THREAD

**Issue by cylewitruk** [stacks-network/sbtc#978]
# Chore - Slow query: `get_swept_deposit_requests`

## 1. Description

The query in this function seems to be getting slower in a relatively linear fashion with the number of blocks ingested. The sample window is relatively short so whether or not this will develop into an exponential regression is unclear. Given that we're already encroaching on 3s avg (from 1.5 two days ago), we're going to need to address this.

![bild](https://github.com/user-attachments/assets/0a05ed3a-a446-42b2-91fe-89a3fe27f958)

## 2. Why It's Necessary

As the graph shows a linear progression of avg elapsed time, this will eventually risk affecting the timing of the signers and their signing rounds, which will be problematic.

**Comment by djordon** [comment]
We can tackle this later but we have an easier fix for this by changing the context window size
