### ISSUE TITLE
[sBTC DR] Figure out what are the right testnet fees to use for sBTC contract calls

### ISSUE THREAD

**Issue by stjepangolemac** [stacks-network/sbtc#98]
https://github.com/stacks-network/sbtc/pull/92#discussion_r1310472469

We don't know how much we should send in fees. All testnet nodes send 1 as the fee rate, constantly.

Let's figure that out.

**Comment by stjepangolemac** [comment]
@kantai do you have any suggestions or guidelines regarding this?

**Comment by friedger** [comment]
There is an api to estimate fees: https://hirosystems.github.io/stacks-blockchain-api/#tag/Fees/operation/post_fee_transaction

**Comment by stjepangolemac** [comment]
We were using the other one to get the fee rate, but it seems fixed to 1 on testnet. I'll look into this, thanks!

**Comment by stjepangolemac** [comment]
We're now using suggested fee info that we get from Stacks and Bitcoin nodes.
