### ISSUE TITLE
[Chore]: pivot to using CONTRACTS_DEPLOYER to fetch SIGNER_AGGREGATE_KEY

### ISSUE THREAD

**Issue by hozzjss** [stacks-network/sbtc#982]
from @matteojug 
> At some point we should pivot to using CONTRACTS_DEPLOYER to fetch SIGNER_AGGREGATE_KEY, so having it in the config is kinda "preliminary work". Also with that information we can derive both the smart contract(s) and the token principal.

**Comment by aldur** [comment]
Isn't what [this](https://github.com/stacks-network/sbtc-bridge/pull/28) is about?
