### ISSUE TITLE
[Feature]: (Partial) Use of `usize` can cause state divergence between signers 

### ISSUE THREAD

**Issue by technovision99** [stacks-network/sbtc#985]
## 1. Description

The use of `usize` in the following function: https://github.com/stacks-network/sbtc/blob/f48d6fe506b06d426cceb8fba5cce21829938a3e/signer/src/transaction_coordinator.rs#L1577-L1597 is not necessary (instead it could just be set to a `u32` to accommodate both 32 and 64 bit archs)  and could cause different signers to process who the coordinator is differently. This could lead to signers being completely out of sync and valid messages being dropped/unsigned.

**Comment by cylewitruk** [comment]
I guess that `u64` shouldn't be a problem either given emulation and 8 bytes would keep the behavior we've been testing with, are you thinking something like this instead (given u64)?

```rust
let index = u64::from_be_bytes(digest[0..8].try_into().unwrap())
```

**Comment by technovision99** [comment]
That should be good, since the use of `u32` and the first 4 bytes of the hash are deterministic among both 32 and 64 bit signers.
