### ISSUE TITLE
[Feature]: (Partial) Signer state modification may not be persisted due to immutable reference

### ISSUE THREAD

**Issue by technovision99** [stacks-network/sbtc#987]
## 1. Description
The `construct_transactions`  function https://github.com/stacks-network/sbtc/blob/f48d6fe506b06d426cceb8fba5cce21829938a3e/signer/src/bitcoin/utxo.rs#L145-L199
has a parameter of `&self` yet the closure directly modifies `self.signer_state` since the closure takes in a mutable reference. This implies that any updates to `self` done through `scan` will not actually be persisted to the `SbtcRequests` struct itself, as the structure operates over the implicitly cloned state instead. Can you take a look as to whether or not this is intended?

**Comment by cylewitruk** [comment]
I'll leave the final comment to @djordon, but I don't believe that the intention here is to actually modify `self`, rather to use the information currently stored in `self` to generate the resulting `Vec<UnsignedTransaction>`, i.e. I believe that the intention here is that calls to `construct_transactions()` should be idempotent.

**Comment by djordon** [comment]
> I'll leave the final comment to @djordon, but I don't believe that the intention here is to actually modify `self`, rather to use the information currently stored in `self` to generate the resulting `Vec<UnsignedTransaction>`, i.e. I believe that the intention here is that calls to `construct_transactions()` should be idempotent.

Yup, that is correct. We depend on the state remaining unmodified after a call to `SbtcRequests::construct_transactions`, which may seem counterintuitive. But yes, this behavior is expected.

**Comment by djordon** [comment]
Closing this, as the current behavior is the desired one.
