### ISSUE TITLE
[Feature]: (High) Hardcoded Postgres login credentials

### ISSUE THREAD

**Issue by technovision99** [stacks-network/sbtc#988]
## 1. Description
The signer documentation https://github.com/stacks-network/sbtc/tree/main/signer#inspecting-the-signer-database states that `Once connected to the database, the signer migrator will create a default user sbtc_user with password sbtc_password which the signer uses to manage the signer state.`
Using these default credentials can allow anyone to compromise the Postgres instance in the event that it is ever exposed over the internet. 

## Recommendation
Switch the default user and password to configurable credentials.

**Comment by cylewitruk** [comment]
The referenced `README.md` is severely out-of-date, thanks for pointing that out. The script that is currently run is:

```sql
-- Create the user if it doesn't exist
DO
$do$
BEGIN
   IF NOT EXISTS (
      SELECT FROM pg_catalog.pg_roles
      WHERE rolname = 'sbtc_user'
   ) THEN
      CREATE USER sbtc_user WITH PASSWORD 'sbtc_password';
   END IF;
END
$do$;
```

Which is largely intended for development purposes. I would be an advocate of not running this script at all unless explicitly requested via a CLI flag i.e. `--create-development-db-user` or something. Thoughts?
