### ISSUE TITLE
[Feature]: Add configurable cap for deposit lock time

### ISSUE THREAD

**Issue by cylewitruk** [stacks-network/sbtc#993]
# Feature - Add configurable cap for deposit lock time

## 1. Description

At present, the deposit lock time can be arbitrarily specified. This implicitly means that the transaction coordinators will perpetually attempt to package deposits which have a very long lock time.

To prevent this, we should add a configurable max-lock-time (suggestion for default: 144 blocks = ~1 day) to prevent the list of pending serviceable requests from becoming too long (especially in the situation where we've hit the total-supply cap).

By doing this, it also allows us to reduce the `context window` parameters to a more reasonable number than the currently hardcoded `10_000` bitcoin blocks, as we'll know the maximum block age of potential deposits.

**Comment by cylewitruk** [comment]
@djordon we touched on this last night, and the signer utxo was a cause for concern since looking for the spendable utxo also uses the context window. Was there something else to add here?

**Comment by djordon** [comment]
I don't think so.

Just thought about the signer's UTXO a bit more, and I think that we can implement that in such a way where we don't require a context window.

**Comment by matteojug** [comment]
As per offline discussion -- we don't actually need this here: given it's just a kind of UX safety net, it's better to handle it in the bridge (we already control the lock time via an env, [source](https://github.com/stacks-network/sbtc-bridge/blob/a19bb7f035623c468fb4a97c715f6709142b66fd/src/actions/get-sbtc-bridge-config.ts#L14) ) and can adjust that based on the context window we decide to use.
People are free to ignore the ~hardcoded~ suggested locktime value at risk of having the funds locked for longer than needed.
